// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: messages_robocup_ssl_wrapper_tracked.proto

package proto.vision;

public final class MessagesRobocupSslWrapperTracked {
  private MessagesRobocupSslWrapperTracked() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface TrackerWrapperPacketOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto.vision.TrackerWrapperPacket)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * A random UUID of the source that is kept constant at the source while running
     * If multiple sources are broadcasting to the same network, this id can be used to identify individual sources
     * </pre>
     *
     * <code>required string uuid = 1;</code>
     */
    boolean hasUuid();
    /**
     * <pre>
     * A random UUID of the source that is kept constant at the source while running
     * If multiple sources are broadcasting to the same network, this id can be used to identify individual sources
     * </pre>
     *
     * <code>required string uuid = 1;</code>
     */
    java.lang.String getUuid();
    /**
     * <pre>
     * A random UUID of the source that is kept constant at the source while running
     * If multiple sources are broadcasting to the same network, this id can be used to identify individual sources
     * </pre>
     *
     * <code>required string uuid = 1;</code>
     */
    com.google.protobuf.ByteString
        getUuidBytes();

    /**
     * <pre>
     * The name of the source software that is producing this messages.
     * </pre>
     *
     * <code>optional string source_name = 2;</code>
     */
    boolean hasSourceName();
    /**
     * <pre>
     * The name of the source software that is producing this messages.
     * </pre>
     *
     * <code>optional string source_name = 2;</code>
     */
    java.lang.String getSourceName();
    /**
     * <pre>
     * The name of the source software that is producing this messages.
     * </pre>
     *
     * <code>optional string source_name = 2;</code>
     */
    com.google.protobuf.ByteString
        getSourceNameBytes();

    /**
     * <pre>
     * The tracked frame
     * </pre>
     *
     * <code>optional .proto.vision.TrackedFrame tracked_frame = 3;</code>
     */
    boolean hasTrackedFrame();
    /**
     * <pre>
     * The tracked frame
     * </pre>
     *
     * <code>optional .proto.vision.TrackedFrame tracked_frame = 3;</code>
     */
    proto.vision.MessagesRobocupSslDetectionTracked.TrackedFrame getTrackedFrame();
    /**
     * <pre>
     * The tracked frame
     * </pre>
     *
     * <code>optional .proto.vision.TrackedFrame tracked_frame = 3;</code>
     */
    proto.vision.MessagesRobocupSslDetectionTracked.TrackedFrameOrBuilder getTrackedFrameOrBuilder();
  }
  /**
   * <pre>
   * A wrapper packet containing meta data of the source
   * Also serves for the possibility to extend the protocol later
   * </pre>
   *
   * Protobuf type {@code proto.vision.TrackerWrapperPacket}
   */
  public  static final class TrackerWrapperPacket extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:proto.vision.TrackerWrapperPacket)
      TrackerWrapperPacketOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use TrackerWrapperPacket.newBuilder() to construct.
    private TrackerWrapperPacket(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private TrackerWrapperPacket() {
      uuid_ = "";
      sourceName_ = "";
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private TrackerWrapperPacket(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              uuid_ = bs;
              break;
            }
            case 18: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000002;
              sourceName_ = bs;
              break;
            }
            case 26: {
              proto.vision.MessagesRobocupSslDetectionTracked.TrackedFrame.Builder subBuilder = null;
              if (((bitField0_ & 0x00000004) == 0x00000004)) {
                subBuilder = trackedFrame_.toBuilder();
              }
              trackedFrame_ = input.readMessage(proto.vision.MessagesRobocupSslDetectionTracked.TrackedFrame.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(trackedFrame_);
                trackedFrame_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000004;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proto.vision.MessagesRobocupSslWrapperTracked.internal_static_proto_vision_TrackerWrapperPacket_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proto.vision.MessagesRobocupSslWrapperTracked.internal_static_proto_vision_TrackerWrapperPacket_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              proto.vision.MessagesRobocupSslWrapperTracked.TrackerWrapperPacket.class, proto.vision.MessagesRobocupSslWrapperTracked.TrackerWrapperPacket.Builder.class);
    }

    private int bitField0_;
    public static final int UUID_FIELD_NUMBER = 1;
    private volatile java.lang.Object uuid_;
    /**
     * <pre>
     * A random UUID of the source that is kept constant at the source while running
     * If multiple sources are broadcasting to the same network, this id can be used to identify individual sources
     * </pre>
     *
     * <code>required string uuid = 1;</code>
     */
    public boolean hasUuid() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <pre>
     * A random UUID of the source that is kept constant at the source while running
     * If multiple sources are broadcasting to the same network, this id can be used to identify individual sources
     * </pre>
     *
     * <code>required string uuid = 1;</code>
     */
    public java.lang.String getUuid() {
      java.lang.Object ref = uuid_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          uuid_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     * A random UUID of the source that is kept constant at the source while running
     * If multiple sources are broadcasting to the same network, this id can be used to identify individual sources
     * </pre>
     *
     * <code>required string uuid = 1;</code>
     */
    public com.google.protobuf.ByteString
        getUuidBytes() {
      java.lang.Object ref = uuid_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        uuid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int SOURCE_NAME_FIELD_NUMBER = 2;
    private volatile java.lang.Object sourceName_;
    /**
     * <pre>
     * The name of the source software that is producing this messages.
     * </pre>
     *
     * <code>optional string source_name = 2;</code>
     */
    public boolean hasSourceName() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <pre>
     * The name of the source software that is producing this messages.
     * </pre>
     *
     * <code>optional string source_name = 2;</code>
     */
    public java.lang.String getSourceName() {
      java.lang.Object ref = sourceName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          sourceName_ = s;
        }
        return s;
      }
    }
    /**
     * <pre>
     * The name of the source software that is producing this messages.
     * </pre>
     *
     * <code>optional string source_name = 2;</code>
     */
    public com.google.protobuf.ByteString
        getSourceNameBytes() {
      java.lang.Object ref = sourceName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        sourceName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TRACKED_FRAME_FIELD_NUMBER = 3;
    private proto.vision.MessagesRobocupSslDetectionTracked.TrackedFrame trackedFrame_;
    /**
     * <pre>
     * The tracked frame
     * </pre>
     *
     * <code>optional .proto.vision.TrackedFrame tracked_frame = 3;</code>
     */
    public boolean hasTrackedFrame() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <pre>
     * The tracked frame
     * </pre>
     *
     * <code>optional .proto.vision.TrackedFrame tracked_frame = 3;</code>
     */
    public proto.vision.MessagesRobocupSslDetectionTracked.TrackedFrame getTrackedFrame() {
      return trackedFrame_ == null ? proto.vision.MessagesRobocupSslDetectionTracked.TrackedFrame.getDefaultInstance() : trackedFrame_;
    }
    /**
     * <pre>
     * The tracked frame
     * </pre>
     *
     * <code>optional .proto.vision.TrackedFrame tracked_frame = 3;</code>
     */
    public proto.vision.MessagesRobocupSslDetectionTracked.TrackedFrameOrBuilder getTrackedFrameOrBuilder() {
      return trackedFrame_ == null ? proto.vision.MessagesRobocupSslDetectionTracked.TrackedFrame.getDefaultInstance() : trackedFrame_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasUuid()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (hasTrackedFrame()) {
        if (!getTrackedFrame().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, uuid_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, sourceName_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeMessage(3, getTrackedFrame());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, uuid_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, sourceName_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getTrackedFrame());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof proto.vision.MessagesRobocupSslWrapperTracked.TrackerWrapperPacket)) {
        return super.equals(obj);
      }
      proto.vision.MessagesRobocupSslWrapperTracked.TrackerWrapperPacket other = (proto.vision.MessagesRobocupSslWrapperTracked.TrackerWrapperPacket) obj;

      boolean result = true;
      result = result && (hasUuid() == other.hasUuid());
      if (hasUuid()) {
        result = result && getUuid()
            .equals(other.getUuid());
      }
      result = result && (hasSourceName() == other.hasSourceName());
      if (hasSourceName()) {
        result = result && getSourceName()
            .equals(other.getSourceName());
      }
      result = result && (hasTrackedFrame() == other.hasTrackedFrame());
      if (hasTrackedFrame()) {
        result = result && getTrackedFrame()
            .equals(other.getTrackedFrame());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasUuid()) {
        hash = (37 * hash) + UUID_FIELD_NUMBER;
        hash = (53 * hash) + getUuid().hashCode();
      }
      if (hasSourceName()) {
        hash = (37 * hash) + SOURCE_NAME_FIELD_NUMBER;
        hash = (53 * hash) + getSourceName().hashCode();
      }
      if (hasTrackedFrame()) {
        hash = (37 * hash) + TRACKED_FRAME_FIELD_NUMBER;
        hash = (53 * hash) + getTrackedFrame().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static proto.vision.MessagesRobocupSslWrapperTracked.TrackerWrapperPacket parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.vision.MessagesRobocupSslWrapperTracked.TrackerWrapperPacket parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.vision.MessagesRobocupSslWrapperTracked.TrackerWrapperPacket parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.vision.MessagesRobocupSslWrapperTracked.TrackerWrapperPacket parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.vision.MessagesRobocupSslWrapperTracked.TrackerWrapperPacket parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.vision.MessagesRobocupSslWrapperTracked.TrackerWrapperPacket parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.vision.MessagesRobocupSslWrapperTracked.TrackerWrapperPacket parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto.vision.MessagesRobocupSslWrapperTracked.TrackerWrapperPacket parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto.vision.MessagesRobocupSslWrapperTracked.TrackerWrapperPacket parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static proto.vision.MessagesRobocupSslWrapperTracked.TrackerWrapperPacket parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto.vision.MessagesRobocupSslWrapperTracked.TrackerWrapperPacket parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto.vision.MessagesRobocupSslWrapperTracked.TrackerWrapperPacket parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(proto.vision.MessagesRobocupSslWrapperTracked.TrackerWrapperPacket prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * A wrapper packet containing meta data of the source
     * Also serves for the possibility to extend the protocol later
     * </pre>
     *
     * Protobuf type {@code proto.vision.TrackerWrapperPacket}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto.vision.TrackerWrapperPacket)
        proto.vision.MessagesRobocupSslWrapperTracked.TrackerWrapperPacketOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return proto.vision.MessagesRobocupSslWrapperTracked.internal_static_proto_vision_TrackerWrapperPacket_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return proto.vision.MessagesRobocupSslWrapperTracked.internal_static_proto_vision_TrackerWrapperPacket_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                proto.vision.MessagesRobocupSslWrapperTracked.TrackerWrapperPacket.class, proto.vision.MessagesRobocupSslWrapperTracked.TrackerWrapperPacket.Builder.class);
      }

      // Construct using proto.vision.MessagesRobocupSslWrapperTracked.TrackerWrapperPacket.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getTrackedFrameFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        uuid_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        sourceName_ = "";
        bitField0_ = (bitField0_ & ~0x00000002);
        if (trackedFrameBuilder_ == null) {
          trackedFrame_ = null;
        } else {
          trackedFrameBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return proto.vision.MessagesRobocupSslWrapperTracked.internal_static_proto_vision_TrackerWrapperPacket_descriptor;
      }

      @java.lang.Override
      public proto.vision.MessagesRobocupSslWrapperTracked.TrackerWrapperPacket getDefaultInstanceForType() {
        return proto.vision.MessagesRobocupSslWrapperTracked.TrackerWrapperPacket.getDefaultInstance();
      }

      @java.lang.Override
      public proto.vision.MessagesRobocupSslWrapperTracked.TrackerWrapperPacket build() {
        proto.vision.MessagesRobocupSslWrapperTracked.TrackerWrapperPacket result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public proto.vision.MessagesRobocupSslWrapperTracked.TrackerWrapperPacket buildPartial() {
        proto.vision.MessagesRobocupSslWrapperTracked.TrackerWrapperPacket result = new proto.vision.MessagesRobocupSslWrapperTracked.TrackerWrapperPacket(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.uuid_ = uuid_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.sourceName_ = sourceName_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        if (trackedFrameBuilder_ == null) {
          result.trackedFrame_ = trackedFrame_;
        } else {
          result.trackedFrame_ = trackedFrameBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof proto.vision.MessagesRobocupSslWrapperTracked.TrackerWrapperPacket) {
          return mergeFrom((proto.vision.MessagesRobocupSslWrapperTracked.TrackerWrapperPacket)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(proto.vision.MessagesRobocupSslWrapperTracked.TrackerWrapperPacket other) {
        if (other == proto.vision.MessagesRobocupSslWrapperTracked.TrackerWrapperPacket.getDefaultInstance()) return this;
        if (other.hasUuid()) {
          bitField0_ |= 0x00000001;
          uuid_ = other.uuid_;
          onChanged();
        }
        if (other.hasSourceName()) {
          bitField0_ |= 0x00000002;
          sourceName_ = other.sourceName_;
          onChanged();
        }
        if (other.hasTrackedFrame()) {
          mergeTrackedFrame(other.getTrackedFrame());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (!hasUuid()) {
          return false;
        }
        if (hasTrackedFrame()) {
          if (!getTrackedFrame().isInitialized()) {
            return false;
          }
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        proto.vision.MessagesRobocupSslWrapperTracked.TrackerWrapperPacket parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (proto.vision.MessagesRobocupSslWrapperTracked.TrackerWrapperPacket) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object uuid_ = "";
      /**
       * <pre>
       * A random UUID of the source that is kept constant at the source while running
       * If multiple sources are broadcasting to the same network, this id can be used to identify individual sources
       * </pre>
       *
       * <code>required string uuid = 1;</code>
       */
      public boolean hasUuid() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <pre>
       * A random UUID of the source that is kept constant at the source while running
       * If multiple sources are broadcasting to the same network, this id can be used to identify individual sources
       * </pre>
       *
       * <code>required string uuid = 1;</code>
       */
      public java.lang.String getUuid() {
        java.lang.Object ref = uuid_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            uuid_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * A random UUID of the source that is kept constant at the source while running
       * If multiple sources are broadcasting to the same network, this id can be used to identify individual sources
       * </pre>
       *
       * <code>required string uuid = 1;</code>
       */
      public com.google.protobuf.ByteString
          getUuidBytes() {
        java.lang.Object ref = uuid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          uuid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * A random UUID of the source that is kept constant at the source while running
       * If multiple sources are broadcasting to the same network, this id can be used to identify individual sources
       * </pre>
       *
       * <code>required string uuid = 1;</code>
       */
      public Builder setUuid(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        uuid_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * A random UUID of the source that is kept constant at the source while running
       * If multiple sources are broadcasting to the same network, this id can be used to identify individual sources
       * </pre>
       *
       * <code>required string uuid = 1;</code>
       */
      public Builder clearUuid() {
        bitField0_ = (bitField0_ & ~0x00000001);
        uuid_ = getDefaultInstance().getUuid();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * A random UUID of the source that is kept constant at the source while running
       * If multiple sources are broadcasting to the same network, this id can be used to identify individual sources
       * </pre>
       *
       * <code>required string uuid = 1;</code>
       */
      public Builder setUuidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        uuid_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object sourceName_ = "";
      /**
       * <pre>
       * The name of the source software that is producing this messages.
       * </pre>
       *
       * <code>optional string source_name = 2;</code>
       */
      public boolean hasSourceName() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <pre>
       * The name of the source software that is producing this messages.
       * </pre>
       *
       * <code>optional string source_name = 2;</code>
       */
      public java.lang.String getSourceName() {
        java.lang.Object ref = sourceName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            sourceName_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * The name of the source software that is producing this messages.
       * </pre>
       *
       * <code>optional string source_name = 2;</code>
       */
      public com.google.protobuf.ByteString
          getSourceNameBytes() {
        java.lang.Object ref = sourceName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          sourceName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * The name of the source software that is producing this messages.
       * </pre>
       *
       * <code>optional string source_name = 2;</code>
       */
      public Builder setSourceName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        sourceName_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The name of the source software that is producing this messages.
       * </pre>
       *
       * <code>optional string source_name = 2;</code>
       */
      public Builder clearSourceName() {
        bitField0_ = (bitField0_ & ~0x00000002);
        sourceName_ = getDefaultInstance().getSourceName();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The name of the source software that is producing this messages.
       * </pre>
       *
       * <code>optional string source_name = 2;</code>
       */
      public Builder setSourceNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        sourceName_ = value;
        onChanged();
        return this;
      }

      private proto.vision.MessagesRobocupSslDetectionTracked.TrackedFrame trackedFrame_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          proto.vision.MessagesRobocupSslDetectionTracked.TrackedFrame, proto.vision.MessagesRobocupSslDetectionTracked.TrackedFrame.Builder, proto.vision.MessagesRobocupSslDetectionTracked.TrackedFrameOrBuilder> trackedFrameBuilder_;
      /**
       * <pre>
       * The tracked frame
       * </pre>
       *
       * <code>optional .proto.vision.TrackedFrame tracked_frame = 3;</code>
       */
      public boolean hasTrackedFrame() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <pre>
       * The tracked frame
       * </pre>
       *
       * <code>optional .proto.vision.TrackedFrame tracked_frame = 3;</code>
       */
      public proto.vision.MessagesRobocupSslDetectionTracked.TrackedFrame getTrackedFrame() {
        if (trackedFrameBuilder_ == null) {
          return trackedFrame_ == null ? proto.vision.MessagesRobocupSslDetectionTracked.TrackedFrame.getDefaultInstance() : trackedFrame_;
        } else {
          return trackedFrameBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       * The tracked frame
       * </pre>
       *
       * <code>optional .proto.vision.TrackedFrame tracked_frame = 3;</code>
       */
      public Builder setTrackedFrame(proto.vision.MessagesRobocupSslDetectionTracked.TrackedFrame value) {
        if (trackedFrameBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          trackedFrame_ = value;
          onChanged();
        } else {
          trackedFrameBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <pre>
       * The tracked frame
       * </pre>
       *
       * <code>optional .proto.vision.TrackedFrame tracked_frame = 3;</code>
       */
      public Builder setTrackedFrame(
          proto.vision.MessagesRobocupSslDetectionTracked.TrackedFrame.Builder builderForValue) {
        if (trackedFrameBuilder_ == null) {
          trackedFrame_ = builderForValue.build();
          onChanged();
        } else {
          trackedFrameBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <pre>
       * The tracked frame
       * </pre>
       *
       * <code>optional .proto.vision.TrackedFrame tracked_frame = 3;</code>
       */
      public Builder mergeTrackedFrame(proto.vision.MessagesRobocupSslDetectionTracked.TrackedFrame value) {
        if (trackedFrameBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004) &&
              trackedFrame_ != null &&
              trackedFrame_ != proto.vision.MessagesRobocupSslDetectionTracked.TrackedFrame.getDefaultInstance()) {
            trackedFrame_ =
              proto.vision.MessagesRobocupSslDetectionTracked.TrackedFrame.newBuilder(trackedFrame_).mergeFrom(value).buildPartial();
          } else {
            trackedFrame_ = value;
          }
          onChanged();
        } else {
          trackedFrameBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <pre>
       * The tracked frame
       * </pre>
       *
       * <code>optional .proto.vision.TrackedFrame tracked_frame = 3;</code>
       */
      public Builder clearTrackedFrame() {
        if (trackedFrameBuilder_ == null) {
          trackedFrame_ = null;
          onChanged();
        } else {
          trackedFrameBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      /**
       * <pre>
       * The tracked frame
       * </pre>
       *
       * <code>optional .proto.vision.TrackedFrame tracked_frame = 3;</code>
       */
      public proto.vision.MessagesRobocupSslDetectionTracked.TrackedFrame.Builder getTrackedFrameBuilder() {
        bitField0_ |= 0x00000004;
        onChanged();
        return getTrackedFrameFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       * The tracked frame
       * </pre>
       *
       * <code>optional .proto.vision.TrackedFrame tracked_frame = 3;</code>
       */
      public proto.vision.MessagesRobocupSslDetectionTracked.TrackedFrameOrBuilder getTrackedFrameOrBuilder() {
        if (trackedFrameBuilder_ != null) {
          return trackedFrameBuilder_.getMessageOrBuilder();
        } else {
          return trackedFrame_ == null ?
              proto.vision.MessagesRobocupSslDetectionTracked.TrackedFrame.getDefaultInstance() : trackedFrame_;
        }
      }
      /**
       * <pre>
       * The tracked frame
       * </pre>
       *
       * <code>optional .proto.vision.TrackedFrame tracked_frame = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          proto.vision.MessagesRobocupSslDetectionTracked.TrackedFrame, proto.vision.MessagesRobocupSslDetectionTracked.TrackedFrame.Builder, proto.vision.MessagesRobocupSslDetectionTracked.TrackedFrameOrBuilder> 
          getTrackedFrameFieldBuilder() {
        if (trackedFrameBuilder_ == null) {
          trackedFrameBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              proto.vision.MessagesRobocupSslDetectionTracked.TrackedFrame, proto.vision.MessagesRobocupSslDetectionTracked.TrackedFrame.Builder, proto.vision.MessagesRobocupSslDetectionTracked.TrackedFrameOrBuilder>(
                  getTrackedFrame(),
                  getParentForChildren(),
                  isClean());
          trackedFrame_ = null;
        }
        return trackedFrameBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:proto.vision.TrackerWrapperPacket)
    }

    // @@protoc_insertion_point(class_scope:proto.vision.TrackerWrapperPacket)
    private static final proto.vision.MessagesRobocupSslWrapperTracked.TrackerWrapperPacket DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new proto.vision.MessagesRobocupSslWrapperTracked.TrackerWrapperPacket();
    }

    public static proto.vision.MessagesRobocupSslWrapperTracked.TrackerWrapperPacket getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<TrackerWrapperPacket>
        PARSER = new com.google.protobuf.AbstractParser<TrackerWrapperPacket>() {
      @java.lang.Override
      public TrackerWrapperPacket parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new TrackerWrapperPacket(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<TrackerWrapperPacket> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TrackerWrapperPacket> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public proto.vision.MessagesRobocupSslWrapperTracked.TrackerWrapperPacket getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_vision_TrackerWrapperPacket_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_vision_TrackerWrapperPacket_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n*messages_robocup_ssl_wrapper_tracked.p" +
      "roto\022\014proto.vision\032,messages_robocup_ssl" +
      "_detection_tracked.proto\"l\n\024TrackerWrapp" +
      "erPacket\022\014\n\004uuid\030\001 \002(\t\022\023\n\013source_name\030\002 " +
      "\001(\t\0221\n\rtracked_frame\030\003 \001(\0132\032.proto.visio" +
      "n.TrackedFrame"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          proto.vision.MessagesRobocupSslDetectionTracked.getDescriptor(),
        }, assigner);
    internal_static_proto_vision_TrackerWrapperPacket_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_proto_vision_TrackerWrapperPacket_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_vision_TrackerWrapperPacket_descriptor,
        new java.lang.String[] { "Uuid", "SourceName", "TrackedFrame", });
    proto.vision.MessagesRobocupSslDetectionTracked.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
