# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ssl_simulation_robot_feedback.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import ssl_simulation_error_pb2 as ssl__simulation__error__pb2
from google.protobuf import any_pb2 as google_dot_protobuf_dot_any__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='ssl_simulation_robot_feedback.proto',
  package='proto.simulation',
  syntax='proto2',
  serialized_options=_b('Z6github.com/RoboCup-SSL/ssl-simulation-protocol/pkg/sim'),
  serialized_pb=_b('\n#ssl_simulation_robot_feedback.proto\x12\x10proto.simulation\x1a\x1assl_simulation_error.proto\x1a\x19google/protobuf/any.proto\"`\n\rRobotFeedback\x12\n\n\x02id\x18\x01 \x02(\r\x12\x1d\n\x15\x64ribbler_ball_contact\x18\x02 \x01(\x08\x12$\n\x06\x63ustom\x18\x03 \x01(\x0b\x32\x14.google.protobuf.Any\"{\n\x14RobotControlResponse\x12\x30\n\x06\x65rrors\x18\x01 \x03(\x0b\x32 .proto.simulation.SimulatorError\x12\x31\n\x08\x66\x65\x65\x64\x62\x61\x63k\x18\x02 \x03(\x0b\x32\x1f.proto.simulation.RobotFeedbackB8Z6github.com/RoboCup-SSL/ssl-simulation-protocol/pkg/sim')
  ,
  dependencies=[ssl__simulation__error__pb2.DESCRIPTOR,google_dot_protobuf_dot_any__pb2.DESCRIPTOR,])




_ROBOTFEEDBACK = _descriptor.Descriptor(
  name='RobotFeedback',
  full_name='proto.simulation.RobotFeedback',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='proto.simulation.RobotFeedback.id', index=0,
      number=1, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='dribbler_ball_contact', full_name='proto.simulation.RobotFeedback.dribbler_ball_contact', index=1,
      number=2, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='custom', full_name='proto.simulation.RobotFeedback.custom', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=112,
  serialized_end=208,
)


_ROBOTCONTROLRESPONSE = _descriptor.Descriptor(
  name='RobotControlResponse',
  full_name='proto.simulation.RobotControlResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='errors', full_name='proto.simulation.RobotControlResponse.errors', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='feedback', full_name='proto.simulation.RobotControlResponse.feedback', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=210,
  serialized_end=333,
)

_ROBOTFEEDBACK.fields_by_name['custom'].message_type = google_dot_protobuf_dot_any__pb2._ANY
_ROBOTCONTROLRESPONSE.fields_by_name['errors'].message_type = ssl__simulation__error__pb2._SIMULATORERROR
_ROBOTCONTROLRESPONSE.fields_by_name['feedback'].message_type = _ROBOTFEEDBACK
DESCRIPTOR.message_types_by_name['RobotFeedback'] = _ROBOTFEEDBACK
DESCRIPTOR.message_types_by_name['RobotControlResponse'] = _ROBOTCONTROLRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RobotFeedback = _reflection.GeneratedProtocolMessageType('RobotFeedback', (_message.Message,), dict(
  DESCRIPTOR = _ROBOTFEEDBACK,
  __module__ = 'ssl_simulation_robot_feedback_pb2'
  # @@protoc_insertion_point(class_scope:proto.simulation.RobotFeedback)
  ))
_sym_db.RegisterMessage(RobotFeedback)

RobotControlResponse = _reflection.GeneratedProtocolMessageType('RobotControlResponse', (_message.Message,), dict(
  DESCRIPTOR = _ROBOTCONTROLRESPONSE,
  __module__ = 'ssl_simulation_robot_feedback_pb2'
  # @@protoc_insertion_point(class_scope:proto.simulation.RobotControlResponse)
  ))
_sym_db.RegisterMessage(RobotControlResponse)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
