# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ssl_simulation_control.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import ssl_gc_common_pb2 as ssl__gc__common__pb2
import ssl_simulation_config_pb2 as ssl__simulation__config__pb2
import ssl_simulation_error_pb2 as ssl__simulation__error__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='ssl_simulation_control.proto',
  package='proto.simulation',
  syntax='proto2',
  serialized_options=_b('Z6github.com/RoboCup-SSL/ssl-simulation-protocol/pkg/sim'),
  serialized_pb=_b('\n\x1cssl_simulation_control.proto\x12\x10proto.simulation\x1a\x13ssl_gc_common.proto\x1a\x1bssl_simulation_config.proto\x1a\x1assl_simulation_error.proto\"\xa1\x01\n\x0cTeleportBall\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\x12\t\n\x01z\x18\x03 \x01(\x02\x12\n\n\x02vx\x18\x04 \x01(\x02\x12\n\n\x02vy\x18\x05 \x01(\x02\x12\n\n\x02vz\x18\x06 \x01(\x02\x12\x1e\n\x0fteleport_safely\x18\x07 \x01(\x08:\x05\x66\x61lse\x12\x13\n\x04roll\x18\x08 \x01(\x08:\x05\x66\x61lse\x12\x17\n\x08\x62y_force\x18\t \x01(\x08:\x05\x66\x61lse\"\xc1\x01\n\rTeleportRobot\x12%\n\x02id\x18\x01 \x02(\x0b\x32\x19.proto.simulation.RobotId\x12\t\n\x01x\x18\x02 \x01(\x02\x12\t\n\x01y\x18\x03 \x01(\x02\x12\x13\n\x0borientation\x18\x04 \x01(\x02\x12\x0e\n\x03v_x\x18\x05 \x01(\x02:\x01\x30\x12\x0e\n\x03v_y\x18\x06 \x01(\x02:\x01\x30\x12\x14\n\tv_angular\x18\x07 \x01(\x02:\x01\x30\x12\x0f\n\x07present\x18\x08 \x01(\x08\x12\x17\n\x08\x62y_force\x18\t \x01(\x08:\x05\x66\x61lse\"\x9c\x01\n\x10SimulatorControl\x12\x35\n\rteleport_ball\x18\x01 \x01(\x0b\x32\x1e.proto.simulation.TeleportBall\x12\x37\n\x0eteleport_robot\x18\x02 \x03(\x0b\x32\x1f.proto.simulation.TeleportRobot\x12\x18\n\x10simulation_speed\x18\x03 \x01(\x02\"z\n\x10SimulatorCommand\x12\x33\n\x07\x63ontrol\x18\x01 \x01(\x0b\x32\".proto.simulation.SimulatorControl\x12\x31\n\x06\x63onfig\x18\x02 \x01(\x0b\x32!.proto.simulation.SimulatorConfig\"E\n\x11SimulatorResponse\x12\x30\n\x06\x65rrors\x18\x01 \x03(\x0b\x32 .proto.simulation.SimulatorErrorB8Z6github.com/RoboCup-SSL/ssl-simulation-protocol/pkg/sim')
  ,
  dependencies=[ssl__gc__common__pb2.DESCRIPTOR,ssl__simulation__config__pb2.DESCRIPTOR,ssl__simulation__error__pb2.DESCRIPTOR,])




_TELEPORTBALL = _descriptor.Descriptor(
  name='TeleportBall',
  full_name='proto.simulation.TeleportBall',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='proto.simulation.TeleportBall.x', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='proto.simulation.TeleportBall.y', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='z', full_name='proto.simulation.TeleportBall.z', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='vx', full_name='proto.simulation.TeleportBall.vx', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='vy', full_name='proto.simulation.TeleportBall.vy', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='vz', full_name='proto.simulation.TeleportBall.vz', index=5,
      number=6, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='teleport_safely', full_name='proto.simulation.TeleportBall.teleport_safely', index=6,
      number=7, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='roll', full_name='proto.simulation.TeleportBall.roll', index=7,
      number=8, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='by_force', full_name='proto.simulation.TeleportBall.by_force', index=8,
      number=9, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=129,
  serialized_end=290,
)


_TELEPORTROBOT = _descriptor.Descriptor(
  name='TeleportRobot',
  full_name='proto.simulation.TeleportRobot',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='proto.simulation.TeleportRobot.id', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='x', full_name='proto.simulation.TeleportRobot.x', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='proto.simulation.TeleportRobot.y', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='orientation', full_name='proto.simulation.TeleportRobot.orientation', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='v_x', full_name='proto.simulation.TeleportRobot.v_x', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='v_y', full_name='proto.simulation.TeleportRobot.v_y', index=5,
      number=6, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='v_angular', full_name='proto.simulation.TeleportRobot.v_angular', index=6,
      number=7, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='present', full_name='proto.simulation.TeleportRobot.present', index=7,
      number=8, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='by_force', full_name='proto.simulation.TeleportRobot.by_force', index=8,
      number=9, type=8, cpp_type=7, label=1,
      has_default_value=True, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=293,
  serialized_end=486,
)


_SIMULATORCONTROL = _descriptor.Descriptor(
  name='SimulatorControl',
  full_name='proto.simulation.SimulatorControl',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='teleport_ball', full_name='proto.simulation.SimulatorControl.teleport_ball', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='teleport_robot', full_name='proto.simulation.SimulatorControl.teleport_robot', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='simulation_speed', full_name='proto.simulation.SimulatorControl.simulation_speed', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=489,
  serialized_end=645,
)


_SIMULATORCOMMAND = _descriptor.Descriptor(
  name='SimulatorCommand',
  full_name='proto.simulation.SimulatorCommand',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='control', full_name='proto.simulation.SimulatorCommand.control', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='config', full_name='proto.simulation.SimulatorCommand.config', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=647,
  serialized_end=769,
)


_SIMULATORRESPONSE = _descriptor.Descriptor(
  name='SimulatorResponse',
  full_name='proto.simulation.SimulatorResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='errors', full_name='proto.simulation.SimulatorResponse.errors', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=771,
  serialized_end=840,
)

_TELEPORTROBOT.fields_by_name['id'].message_type = ssl__gc__common__pb2._ROBOTID
_SIMULATORCONTROL.fields_by_name['teleport_ball'].message_type = _TELEPORTBALL
_SIMULATORCONTROL.fields_by_name['teleport_robot'].message_type = _TELEPORTROBOT
_SIMULATORCOMMAND.fields_by_name['control'].message_type = _SIMULATORCONTROL
_SIMULATORCOMMAND.fields_by_name['config'].message_type = ssl__simulation__config__pb2._SIMULATORCONFIG
_SIMULATORRESPONSE.fields_by_name['errors'].message_type = ssl__simulation__error__pb2._SIMULATORERROR
DESCRIPTOR.message_types_by_name['TeleportBall'] = _TELEPORTBALL
DESCRIPTOR.message_types_by_name['TeleportRobot'] = _TELEPORTROBOT
DESCRIPTOR.message_types_by_name['SimulatorControl'] = _SIMULATORCONTROL
DESCRIPTOR.message_types_by_name['SimulatorCommand'] = _SIMULATORCOMMAND
DESCRIPTOR.message_types_by_name['SimulatorResponse'] = _SIMULATORRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TeleportBall = _reflection.GeneratedProtocolMessageType('TeleportBall', (_message.Message,), dict(
  DESCRIPTOR = _TELEPORTBALL,
  __module__ = 'ssl_simulation_control_pb2'
  # @@protoc_insertion_point(class_scope:proto.simulation.TeleportBall)
  ))
_sym_db.RegisterMessage(TeleportBall)

TeleportRobot = _reflection.GeneratedProtocolMessageType('TeleportRobot', (_message.Message,), dict(
  DESCRIPTOR = _TELEPORTROBOT,
  __module__ = 'ssl_simulation_control_pb2'
  # @@protoc_insertion_point(class_scope:proto.simulation.TeleportRobot)
  ))
_sym_db.RegisterMessage(TeleportRobot)

SimulatorControl = _reflection.GeneratedProtocolMessageType('SimulatorControl', (_message.Message,), dict(
  DESCRIPTOR = _SIMULATORCONTROL,
  __module__ = 'ssl_simulation_control_pb2'
  # @@protoc_insertion_point(class_scope:proto.simulation.SimulatorControl)
  ))
_sym_db.RegisterMessage(SimulatorControl)

SimulatorCommand = _reflection.GeneratedProtocolMessageType('SimulatorCommand', (_message.Message,), dict(
  DESCRIPTOR = _SIMULATORCOMMAND,
  __module__ = 'ssl_simulation_control_pb2'
  # @@protoc_insertion_point(class_scope:proto.simulation.SimulatorCommand)
  ))
_sym_db.RegisterMessage(SimulatorCommand)

SimulatorResponse = _reflection.GeneratedProtocolMessageType('SimulatorResponse', (_message.Message,), dict(
  DESCRIPTOR = _SIMULATORRESPONSE,
  __module__ = 'ssl_simulation_control_pb2'
  # @@protoc_insertion_point(class_scope:proto.simulation.SimulatorResponse)
  ))
_sym_db.RegisterMessage(SimulatorResponse)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
