# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ssl_simulation_synchronous.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import ssl_vision_detection_pb2 as ssl__vision__detection__pb2
import ssl_simulation_robot_feedback_pb2 as ssl__simulation__robot__feedback__pb2
import ssl_simulation_robot_control_pb2 as ssl__simulation__robot__control__pb2
import ssl_simulation_control_pb2 as ssl__simulation__control__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='ssl_simulation_synchronous.proto',
  package='proto.simulation',
  syntax='proto2',
  serialized_options=_b('Z6github.com/RoboCup-SSL/ssl-simulation-protocol/pkg/sim'),
  serialized_pb=_b('\n ssl_simulation_synchronous.proto\x12\x10proto.simulation\x1a\x1assl_vision_detection.proto\x1a#ssl_simulation_robot_feedback.proto\x1a\"ssl_simulation_robot_control.proto\x1a\x1cssl_simulation_control.proto\"\x9f\x01\n\x15SimulationSyncRequest\x12\x10\n\x08sim_step\x18\x01 \x01(\x02\x12=\n\x11simulator_command\x18\x02 \x01(\x0b\x32\".proto.simulation.SimulatorCommand\x12\x35\n\rrobot_control\x18\x03 \x01(\x0b\x32\x1e.proto.simulation.RobotControl\"\x99\x01\n\x16SimulationSyncResponse\x12\x37\n\tdetection\x18\x01 \x03(\x0b\x32$.proto.simulation.SSL_DetectionFrame\x12\x46\n\x16robot_control_response\x18\x02 \x01(\x0b\x32&.proto.simulation.RobotControlResponseB8Z6github.com/RoboCup-SSL/ssl-simulation-protocol/pkg/sim')
  ,
  dependencies=[ssl__vision__detection__pb2.DESCRIPTOR,ssl__simulation__robot__feedback__pb2.DESCRIPTOR,ssl__simulation__robot__control__pb2.DESCRIPTOR,ssl__simulation__control__pb2.DESCRIPTOR,])




_SIMULATIONSYNCREQUEST = _descriptor.Descriptor(
  name='SimulationSyncRequest',
  full_name='proto.simulation.SimulationSyncRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='sim_step', full_name='proto.simulation.SimulationSyncRequest.sim_step', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='simulator_command', full_name='proto.simulation.SimulationSyncRequest.simulator_command', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='robot_control', full_name='proto.simulation.SimulationSyncRequest.robot_control', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=186,
  serialized_end=345,
)


_SIMULATIONSYNCRESPONSE = _descriptor.Descriptor(
  name='SimulationSyncResponse',
  full_name='proto.simulation.SimulationSyncResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='detection', full_name='proto.simulation.SimulationSyncResponse.detection', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='robot_control_response', full_name='proto.simulation.SimulationSyncResponse.robot_control_response', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=348,
  serialized_end=501,
)

_SIMULATIONSYNCREQUEST.fields_by_name['simulator_command'].message_type = ssl__simulation__control__pb2._SIMULATORCOMMAND
_SIMULATIONSYNCREQUEST.fields_by_name['robot_control'].message_type = ssl__simulation__robot__control__pb2._ROBOTCONTROL
_SIMULATIONSYNCRESPONSE.fields_by_name['detection'].message_type = ssl__vision__detection__pb2._SSL_DETECTIONFRAME
_SIMULATIONSYNCRESPONSE.fields_by_name['robot_control_response'].message_type = ssl__simulation__robot__feedback__pb2._ROBOTCONTROLRESPONSE
DESCRIPTOR.message_types_by_name['SimulationSyncRequest'] = _SIMULATIONSYNCREQUEST
DESCRIPTOR.message_types_by_name['SimulationSyncResponse'] = _SIMULATIONSYNCRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SimulationSyncRequest = _reflection.GeneratedProtocolMessageType('SimulationSyncRequest', (_message.Message,), dict(
  DESCRIPTOR = _SIMULATIONSYNCREQUEST,
  __module__ = 'ssl_simulation_synchronous_pb2'
  # @@protoc_insertion_point(class_scope:proto.simulation.SimulationSyncRequest)
  ))
_sym_db.RegisterMessage(SimulationSyncRequest)

SimulationSyncResponse = _reflection.GeneratedProtocolMessageType('SimulationSyncResponse', (_message.Message,), dict(
  DESCRIPTOR = _SIMULATIONSYNCRESPONSE,
  __module__ = 'ssl_simulation_synchronous_pb2'
  # @@protoc_insertion_point(class_scope:proto.simulation.SimulationSyncResponse)
  ))
_sym_db.RegisterMessage(SimulationSyncResponse)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
