# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: triton_bot_init.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='triton_bot_init.proto',
  package='proto.triton',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x15triton_bot_init.proto\x12\x0cproto.triton\"\x12\n\x04Init\x12\n\n\x02id\x18\x01 \x01(\x05\x62\x06proto3')
)




_INIT = _descriptor.Descriptor(
  name='Init',
  full_name='proto.triton.Init',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='proto.triton.Init.id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=39,
  serialized_end=57,
)

DESCRIPTOR.message_types_by_name['Init'] = _INIT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Init = _reflection.GeneratedProtocolMessageType('Init', (_message.Message,), dict(
  DESCRIPTOR = _INIT,
  __module__ = 'triton_bot_init_pb2'
  # @@protoc_insertion_point(class_scope:proto.triton.Init)
  ))
_sym_db.RegisterMessage(Init)


# @@protoc_insertion_point(module_scope)
