package com.triton.messaging;

public enum Exchange {
    // CAMERA
    AI_VISION_WRAPPER,

    // PROCESSED VISION INFORMATION
    AI_BIASED_FIELD,
    AI_BIASED_BALLS,
    AI_BIASED_ALLIES,
    AI_BIASED_FOES,

    // WILL BE CONVERTED BEFORE BEING SENT
    AI_BIASED_SIMULATOR_COMMAND,
    AI_BIASED_ROBOT_CONTROL,
    AI_BIASED_ROBOT_COMMAND,

    // CAN BE SENT DIRECTLY
    AI_SIMULATOR_COMMAND,
    AI_ROBOT_COMMAND,
    AI_TRITON_BOT_COMMAND,
}