package com.triton.messaging;

public enum Exchange {
    AI_RAW_WRAPPER_PACKAGE,
    AI_BIASED_FIELD,
    AI_BIASED_BALLS,
    AI_BIASED_ALLIES,
    AI_BIASED_FOES,
    AI_SIMULATOR_COMMAND,
    AI_ROBOT_CONTROL,
    AI_TRITON_BOT_COMMAND,
}