// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ssl_gc_common.proto

package proto.simulation;

public final class SslGcCommon {
  private SslGcCommon() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * <pre>
   * Team is either blue or yellow
   * </pre>
   *
   * Protobuf enum {@code proto.simulation.Team}
   */
  public enum Team
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     * team not set
     * </pre>
     *
     * <code>UNKNOWN = 0;</code>
     */
    UNKNOWN(0),
    /**
     * <pre>
     * yellow team
     * </pre>
     *
     * <code>YELLOW = 1;</code>
     */
    YELLOW(1),
    /**
     * <pre>
     * blue team
     * </pre>
     *
     * <code>BLUE = 2;</code>
     */
    BLUE(2),
    ;

    /**
     * <pre>
     * team not set
     * </pre>
     *
     * <code>UNKNOWN = 0;</code>
     */
    public static final int UNKNOWN_VALUE = 0;
    /**
     * <pre>
     * yellow team
     * </pre>
     *
     * <code>YELLOW = 1;</code>
     */
    public static final int YELLOW_VALUE = 1;
    /**
     * <pre>
     * blue team
     * </pre>
     *
     * <code>BLUE = 2;</code>
     */
    public static final int BLUE_VALUE = 2;


    public final int getNumber() {
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static Team valueOf(int value) {
      return forNumber(value);
    }

    public static Team forNumber(int value) {
      switch (value) {
        case 0: return UNKNOWN;
        case 1: return YELLOW;
        case 2: return BLUE;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Team>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Team> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Team>() {
            public Team findValueByNumber(int number) {
              return Team.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return proto.simulation.SslGcCommon.getDescriptor().getEnumTypes().get(0);
    }

    private static final Team[] VALUES = values();

    public static Team valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private Team(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:proto.simulation.Team)
  }

  /**
   * <pre>
   * Division denotes the current division, which influences some rules
   * </pre>
   *
   * Protobuf enum {@code proto.simulation.Division}
   */
  public enum Division
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>DIV_UNKNOWN = 0;</code>
     */
    DIV_UNKNOWN(0),
    /**
     * <code>DIV_A = 1;</code>
     */
    DIV_A(1),
    /**
     * <code>DIV_B = 2;</code>
     */
    DIV_B(2),
    ;

    /**
     * <code>DIV_UNKNOWN = 0;</code>
     */
    public static final int DIV_UNKNOWN_VALUE = 0;
    /**
     * <code>DIV_A = 1;</code>
     */
    public static final int DIV_A_VALUE = 1;
    /**
     * <code>DIV_B = 2;</code>
     */
    public static final int DIV_B_VALUE = 2;


    public final int getNumber() {
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static Division valueOf(int value) {
      return forNumber(value);
    }

    public static Division forNumber(int value) {
      switch (value) {
        case 0: return DIV_UNKNOWN;
        case 1: return DIV_A;
        case 2: return DIV_B;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Division>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Division> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Division>() {
            public Division findValueByNumber(int number) {
              return Division.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return proto.simulation.SslGcCommon.getDescriptor().getEnumTypes().get(1);
    }

    private static final Division[] VALUES = values();

    public static Division valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private Division(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:proto.simulation.Division)
  }

  public interface RobotIdOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto.simulation.RobotId)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * the robot number
     * </pre>
     *
     * <code>optional uint32 id = 1;</code>
     */
    boolean hasId();
    /**
     * <pre>
     * the robot number
     * </pre>
     *
     * <code>optional uint32 id = 1;</code>
     */
    int getId();

    /**
     * <pre>
     * the team that the robot belongs to
     * </pre>
     *
     * <code>optional .proto.simulation.Team team = 2;</code>
     */
    boolean hasTeam();
    /**
     * <pre>
     * the team that the robot belongs to
     * </pre>
     *
     * <code>optional .proto.simulation.Team team = 2;</code>
     */
    proto.simulation.SslGcCommon.Team getTeam();
  }
  /**
   * <pre>
   * RobotId is the combination of a team and a robot id
   * </pre>
   *
   * Protobuf type {@code proto.simulation.RobotId}
   */
  public  static final class RobotId extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:proto.simulation.RobotId)
      RobotIdOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use RobotId.newBuilder() to construct.
    private RobotId(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private RobotId() {
      id_ = 0;
      team_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private RobotId(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readUInt32();
              break;
            }
            case 16: {
              int rawValue = input.readEnum();
                @SuppressWarnings("deprecation")
              proto.simulation.SslGcCommon.Team value = proto.simulation.SslGcCommon.Team.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(2, rawValue);
              } else {
                bitField0_ |= 0x00000002;
                team_ = rawValue;
              }
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proto.simulation.SslGcCommon.internal_static_proto_simulation_RobotId_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proto.simulation.SslGcCommon.internal_static_proto_simulation_RobotId_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              proto.simulation.SslGcCommon.RobotId.class, proto.simulation.SslGcCommon.RobotId.Builder.class);
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <pre>
     * the robot number
     * </pre>
     *
     * <code>optional uint32 id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <pre>
     * the robot number
     * </pre>
     *
     * <code>optional uint32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }

    public static final int TEAM_FIELD_NUMBER = 2;
    private int team_;
    /**
     * <pre>
     * the team that the robot belongs to
     * </pre>
     *
     * <code>optional .proto.simulation.Team team = 2;</code>
     */
    public boolean hasTeam() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <pre>
     * the team that the robot belongs to
     * </pre>
     *
     * <code>optional .proto.simulation.Team team = 2;</code>
     */
    public proto.simulation.SslGcCommon.Team getTeam() {
      @SuppressWarnings("deprecation")
      proto.simulation.SslGcCommon.Team result = proto.simulation.SslGcCommon.Team.valueOf(team_);
      return result == null ? proto.simulation.SslGcCommon.Team.UNKNOWN : result;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeUInt32(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeEnum(2, team_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, team_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof proto.simulation.SslGcCommon.RobotId)) {
        return super.equals(obj);
      }
      proto.simulation.SslGcCommon.RobotId other = (proto.simulation.SslGcCommon.RobotId) obj;

      boolean result = true;
      result = result && (hasId() == other.hasId());
      if (hasId()) {
        result = result && (getId()
            == other.getId());
      }
      result = result && (hasTeam() == other.hasTeam());
      if (hasTeam()) {
        result = result && team_ == other.team_;
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasId()) {
        hash = (37 * hash) + ID_FIELD_NUMBER;
        hash = (53 * hash) + getId();
      }
      if (hasTeam()) {
        hash = (37 * hash) + TEAM_FIELD_NUMBER;
        hash = (53 * hash) + team_;
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static proto.simulation.SslGcCommon.RobotId parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.simulation.SslGcCommon.RobotId parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.simulation.SslGcCommon.RobotId parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.simulation.SslGcCommon.RobotId parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.simulation.SslGcCommon.RobotId parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.simulation.SslGcCommon.RobotId parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.simulation.SslGcCommon.RobotId parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto.simulation.SslGcCommon.RobotId parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto.simulation.SslGcCommon.RobotId parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static proto.simulation.SslGcCommon.RobotId parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto.simulation.SslGcCommon.RobotId parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto.simulation.SslGcCommon.RobotId parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(proto.simulation.SslGcCommon.RobotId prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * RobotId is the combination of a team and a robot id
     * </pre>
     *
     * Protobuf type {@code proto.simulation.RobotId}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto.simulation.RobotId)
        proto.simulation.SslGcCommon.RobotIdOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return proto.simulation.SslGcCommon.internal_static_proto_simulation_RobotId_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return proto.simulation.SslGcCommon.internal_static_proto_simulation_RobotId_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                proto.simulation.SslGcCommon.RobotId.class, proto.simulation.SslGcCommon.RobotId.Builder.class);
      }

      // Construct using proto.simulation.SslGcCommon.RobotId.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        id_ = 0;
        bitField0_ = (bitField0_ & ~0x00000001);
        team_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return proto.simulation.SslGcCommon.internal_static_proto_simulation_RobotId_descriptor;
      }

      @java.lang.Override
      public proto.simulation.SslGcCommon.RobotId getDefaultInstanceForType() {
        return proto.simulation.SslGcCommon.RobotId.getDefaultInstance();
      }

      @java.lang.Override
      public proto.simulation.SslGcCommon.RobotId build() {
        proto.simulation.SslGcCommon.RobotId result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public proto.simulation.SslGcCommon.RobotId buildPartial() {
        proto.simulation.SslGcCommon.RobotId result = new proto.simulation.SslGcCommon.RobotId(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.team_ = team_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof proto.simulation.SslGcCommon.RobotId) {
          return mergeFrom((proto.simulation.SslGcCommon.RobotId)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(proto.simulation.SslGcCommon.RobotId other) {
        if (other == proto.simulation.SslGcCommon.RobotId.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasTeam()) {
          setTeam(other.getTeam());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        proto.simulation.SslGcCommon.RobotId parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (proto.simulation.SslGcCommon.RobotId) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private int id_ ;
      /**
       * <pre>
       * the robot number
       * </pre>
       *
       * <code>optional uint32 id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <pre>
       * the robot number
       * </pre>
       *
       * <code>optional uint32 id = 1;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <pre>
       * the robot number
       * </pre>
       *
       * <code>optional uint32 id = 1;</code>
       */
      public Builder setId(int value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * the robot number
       * </pre>
       *
       * <code>optional uint32 id = 1;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        onChanged();
        return this;
      }

      private int team_ = 0;
      /**
       * <pre>
       * the team that the robot belongs to
       * </pre>
       *
       * <code>optional .proto.simulation.Team team = 2;</code>
       */
      public boolean hasTeam() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <pre>
       * the team that the robot belongs to
       * </pre>
       *
       * <code>optional .proto.simulation.Team team = 2;</code>
       */
      public proto.simulation.SslGcCommon.Team getTeam() {
        @SuppressWarnings("deprecation")
        proto.simulation.SslGcCommon.Team result = proto.simulation.SslGcCommon.Team.valueOf(team_);
        return result == null ? proto.simulation.SslGcCommon.Team.UNKNOWN : result;
      }
      /**
       * <pre>
       * the team that the robot belongs to
       * </pre>
       *
       * <code>optional .proto.simulation.Team team = 2;</code>
       */
      public Builder setTeam(proto.simulation.SslGcCommon.Team value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        team_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * the team that the robot belongs to
       * </pre>
       *
       * <code>optional .proto.simulation.Team team = 2;</code>
       */
      public Builder clearTeam() {
        bitField0_ = (bitField0_ & ~0x00000002);
        team_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:proto.simulation.RobotId)
    }

    // @@protoc_insertion_point(class_scope:proto.simulation.RobotId)
    private static final proto.simulation.SslGcCommon.RobotId DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new proto.simulation.SslGcCommon.RobotId();
    }

    public static proto.simulation.SslGcCommon.RobotId getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<RobotId>
        PARSER = new com.google.protobuf.AbstractParser<RobotId>() {
      @java.lang.Override
      public RobotId parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new RobotId(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<RobotId> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<RobotId> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public proto.simulation.SslGcCommon.RobotId getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_simulation_RobotId_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_simulation_RobotId_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023ssl_gc_common.proto\022\020proto.simulation\"" +
      ";\n\007RobotId\022\n\n\002id\030\001 \001(\r\022$\n\004team\030\002 \001(\0162\026.p" +
      "roto.simulation.Team*)\n\004Team\022\013\n\007UNKNOWN\020" +
      "\000\022\n\n\006YELLOW\020\001\022\010\n\004BLUE\020\002*1\n\010Division\022\017\n\013D" +
      "IV_UNKNOWN\020\000\022\t\n\005DIV_A\020\001\022\t\n\005DIV_B\020\002B8Z6gi" +
      "thub.com/RoboCup-SSL/ssl-simulation-prot" +
      "ocol/pkg/sim"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_proto_simulation_RobotId_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_proto_simulation_RobotId_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_simulation_RobotId_descriptor,
        new java.lang.String[] { "Id", "Team", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
