// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ssl_simulation_synchronous.proto

package proto.simulation;

public final class SslSimulationSynchronous {
  private SslSimulationSynchronous() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface SimulationSyncRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto.simulation.SimulationSyncRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * The simulation step [s] to perform
     * </pre>
     *
     * <code>optional float sim_step = 1;</code>
     */
    boolean hasSimStep();
    /**
     * <pre>
     * The simulation step [s] to perform
     * </pre>
     *
     * <code>optional float sim_step = 1;</code>
     */
    float getSimStep();

    /**
     * <pre>
     * An optional simulator command
     * </pre>
     *
     * <code>optional .proto.simulation.SimulatorCommand simulator_command = 2;</code>
     */
    boolean hasSimulatorCommand();
    /**
     * <pre>
     * An optional simulator command
     * </pre>
     *
     * <code>optional .proto.simulation.SimulatorCommand simulator_command = 2;</code>
     */
    proto.simulation.SslSimulationControl.SimulatorCommand getSimulatorCommand();
    /**
     * <pre>
     * An optional simulator command
     * </pre>
     *
     * <code>optional .proto.simulation.SimulatorCommand simulator_command = 2;</code>
     */
    proto.simulation.SslSimulationControl.SimulatorCommandOrBuilder getSimulatorCommandOrBuilder();

    /**
     * <pre>
     * An optional robot control command
     * </pre>
     *
     * <code>optional .proto.simulation.RobotControl robot_control = 3;</code>
     */
    boolean hasRobotControl();
    /**
     * <pre>
     * An optional robot control command
     * </pre>
     *
     * <code>optional .proto.simulation.RobotControl robot_control = 3;</code>
     */
    proto.simulation.SslSimulationRobotControl.RobotControl getRobotControl();
    /**
     * <pre>
     * An optional robot control command
     * </pre>
     *
     * <code>optional .proto.simulation.RobotControl robot_control = 3;</code>
     */
    proto.simulation.SslSimulationRobotControl.RobotControlOrBuilder getRobotControlOrBuilder();
  }
  /**
   * <pre>
   * Request from the team to the simulator
   * </pre>
   *
   * Protobuf type {@code proto.simulation.SimulationSyncRequest}
   */
  public  static final class SimulationSyncRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:proto.simulation.SimulationSyncRequest)
      SimulationSyncRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SimulationSyncRequest.newBuilder() to construct.
    private SimulationSyncRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SimulationSyncRequest() {
      simStep_ = 0F;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SimulationSyncRequest(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 13: {
              bitField0_ |= 0x00000001;
              simStep_ = input.readFloat();
              break;
            }
            case 18: {
              proto.simulation.SslSimulationControl.SimulatorCommand.Builder subBuilder = null;
              if (((bitField0_ & 0x00000002) == 0x00000002)) {
                subBuilder = simulatorCommand_.toBuilder();
              }
              simulatorCommand_ = input.readMessage(proto.simulation.SslSimulationControl.SimulatorCommand.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(simulatorCommand_);
                simulatorCommand_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000002;
              break;
            }
            case 26: {
              proto.simulation.SslSimulationRobotControl.RobotControl.Builder subBuilder = null;
              if (((bitField0_ & 0x00000004) == 0x00000004)) {
                subBuilder = robotControl_.toBuilder();
              }
              robotControl_ = input.readMessage(proto.simulation.SslSimulationRobotControl.RobotControl.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(robotControl_);
                robotControl_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000004;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proto.simulation.SslSimulationSynchronous.internal_static_proto_simulation_SimulationSyncRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proto.simulation.SslSimulationSynchronous.internal_static_proto_simulation_SimulationSyncRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              proto.simulation.SslSimulationSynchronous.SimulationSyncRequest.class, proto.simulation.SslSimulationSynchronous.SimulationSyncRequest.Builder.class);
    }

    private int bitField0_;
    public static final int SIM_STEP_FIELD_NUMBER = 1;
    private float simStep_;
    /**
     * <pre>
     * The simulation step [s] to perform
     * </pre>
     *
     * <code>optional float sim_step = 1;</code>
     */
    public boolean hasSimStep() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <pre>
     * The simulation step [s] to perform
     * </pre>
     *
     * <code>optional float sim_step = 1;</code>
     */
    public float getSimStep() {
      return simStep_;
    }

    public static final int SIMULATOR_COMMAND_FIELD_NUMBER = 2;
    private proto.simulation.SslSimulationControl.SimulatorCommand simulatorCommand_;
    /**
     * <pre>
     * An optional simulator command
     * </pre>
     *
     * <code>optional .proto.simulation.SimulatorCommand simulator_command = 2;</code>
     */
    public boolean hasSimulatorCommand() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <pre>
     * An optional simulator command
     * </pre>
     *
     * <code>optional .proto.simulation.SimulatorCommand simulator_command = 2;</code>
     */
    public proto.simulation.SslSimulationControl.SimulatorCommand getSimulatorCommand() {
      return simulatorCommand_ == null ? proto.simulation.SslSimulationControl.SimulatorCommand.getDefaultInstance() : simulatorCommand_;
    }
    /**
     * <pre>
     * An optional simulator command
     * </pre>
     *
     * <code>optional .proto.simulation.SimulatorCommand simulator_command = 2;</code>
     */
    public proto.simulation.SslSimulationControl.SimulatorCommandOrBuilder getSimulatorCommandOrBuilder() {
      return simulatorCommand_ == null ? proto.simulation.SslSimulationControl.SimulatorCommand.getDefaultInstance() : simulatorCommand_;
    }

    public static final int ROBOT_CONTROL_FIELD_NUMBER = 3;
    private proto.simulation.SslSimulationRobotControl.RobotControl robotControl_;
    /**
     * <pre>
     * An optional robot control command
     * </pre>
     *
     * <code>optional .proto.simulation.RobotControl robot_control = 3;</code>
     */
    public boolean hasRobotControl() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <pre>
     * An optional robot control command
     * </pre>
     *
     * <code>optional .proto.simulation.RobotControl robot_control = 3;</code>
     */
    public proto.simulation.SslSimulationRobotControl.RobotControl getRobotControl() {
      return robotControl_ == null ? proto.simulation.SslSimulationRobotControl.RobotControl.getDefaultInstance() : robotControl_;
    }
    /**
     * <pre>
     * An optional robot control command
     * </pre>
     *
     * <code>optional .proto.simulation.RobotControl robot_control = 3;</code>
     */
    public proto.simulation.SslSimulationRobotControl.RobotControlOrBuilder getRobotControlOrBuilder() {
      return robotControl_ == null ? proto.simulation.SslSimulationRobotControl.RobotControl.getDefaultInstance() : robotControl_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (hasSimulatorCommand()) {
        if (!getSimulatorCommand().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      if (hasRobotControl()) {
        if (!getRobotControl().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeFloat(1, simStep_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(2, getSimulatorCommand());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeMessage(3, getRobotControl());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(1, simStep_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getSimulatorCommand());
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getRobotControl());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof proto.simulation.SslSimulationSynchronous.SimulationSyncRequest)) {
        return super.equals(obj);
      }
      proto.simulation.SslSimulationSynchronous.SimulationSyncRequest other = (proto.simulation.SslSimulationSynchronous.SimulationSyncRequest) obj;

      boolean result = true;
      result = result && (hasSimStep() == other.hasSimStep());
      if (hasSimStep()) {
        result = result && (
            java.lang.Float.floatToIntBits(getSimStep())
            == java.lang.Float.floatToIntBits(
                other.getSimStep()));
      }
      result = result && (hasSimulatorCommand() == other.hasSimulatorCommand());
      if (hasSimulatorCommand()) {
        result = result && getSimulatorCommand()
            .equals(other.getSimulatorCommand());
      }
      result = result && (hasRobotControl() == other.hasRobotControl());
      if (hasRobotControl()) {
        result = result && getRobotControl()
            .equals(other.getRobotControl());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasSimStep()) {
        hash = (37 * hash) + SIM_STEP_FIELD_NUMBER;
        hash = (53 * hash) + java.lang.Float.floatToIntBits(
            getSimStep());
      }
      if (hasSimulatorCommand()) {
        hash = (37 * hash) + SIMULATOR_COMMAND_FIELD_NUMBER;
        hash = (53 * hash) + getSimulatorCommand().hashCode();
      }
      if (hasRobotControl()) {
        hash = (37 * hash) + ROBOT_CONTROL_FIELD_NUMBER;
        hash = (53 * hash) + getRobotControl().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static proto.simulation.SslSimulationSynchronous.SimulationSyncRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.simulation.SslSimulationSynchronous.SimulationSyncRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.simulation.SslSimulationSynchronous.SimulationSyncRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.simulation.SslSimulationSynchronous.SimulationSyncRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.simulation.SslSimulationSynchronous.SimulationSyncRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.simulation.SslSimulationSynchronous.SimulationSyncRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.simulation.SslSimulationSynchronous.SimulationSyncRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto.simulation.SslSimulationSynchronous.SimulationSyncRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto.simulation.SslSimulationSynchronous.SimulationSyncRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static proto.simulation.SslSimulationSynchronous.SimulationSyncRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto.simulation.SslSimulationSynchronous.SimulationSyncRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto.simulation.SslSimulationSynchronous.SimulationSyncRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(proto.simulation.SslSimulationSynchronous.SimulationSyncRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Request from the team to the simulator
     * </pre>
     *
     * Protobuf type {@code proto.simulation.SimulationSyncRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto.simulation.SimulationSyncRequest)
        proto.simulation.SslSimulationSynchronous.SimulationSyncRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return proto.simulation.SslSimulationSynchronous.internal_static_proto_simulation_SimulationSyncRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return proto.simulation.SslSimulationSynchronous.internal_static_proto_simulation_SimulationSyncRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                proto.simulation.SslSimulationSynchronous.SimulationSyncRequest.class, proto.simulation.SslSimulationSynchronous.SimulationSyncRequest.Builder.class);
      }

      // Construct using proto.simulation.SslSimulationSynchronous.SimulationSyncRequest.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getSimulatorCommandFieldBuilder();
          getRobotControlFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        simStep_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (simulatorCommandBuilder_ == null) {
          simulatorCommand_ = null;
        } else {
          simulatorCommandBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        if (robotControlBuilder_ == null) {
          robotControl_ = null;
        } else {
          robotControlBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return proto.simulation.SslSimulationSynchronous.internal_static_proto_simulation_SimulationSyncRequest_descriptor;
      }

      @java.lang.Override
      public proto.simulation.SslSimulationSynchronous.SimulationSyncRequest getDefaultInstanceForType() {
        return proto.simulation.SslSimulationSynchronous.SimulationSyncRequest.getDefaultInstance();
      }

      @java.lang.Override
      public proto.simulation.SslSimulationSynchronous.SimulationSyncRequest build() {
        proto.simulation.SslSimulationSynchronous.SimulationSyncRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public proto.simulation.SslSimulationSynchronous.SimulationSyncRequest buildPartial() {
        proto.simulation.SslSimulationSynchronous.SimulationSyncRequest result = new proto.simulation.SslSimulationSynchronous.SimulationSyncRequest(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.simStep_ = simStep_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        if (simulatorCommandBuilder_ == null) {
          result.simulatorCommand_ = simulatorCommand_;
        } else {
          result.simulatorCommand_ = simulatorCommandBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        if (robotControlBuilder_ == null) {
          result.robotControl_ = robotControl_;
        } else {
          result.robotControl_ = robotControlBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof proto.simulation.SslSimulationSynchronous.SimulationSyncRequest) {
          return mergeFrom((proto.simulation.SslSimulationSynchronous.SimulationSyncRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(proto.simulation.SslSimulationSynchronous.SimulationSyncRequest other) {
        if (other == proto.simulation.SslSimulationSynchronous.SimulationSyncRequest.getDefaultInstance()) return this;
        if (other.hasSimStep()) {
          setSimStep(other.getSimStep());
        }
        if (other.hasSimulatorCommand()) {
          mergeSimulatorCommand(other.getSimulatorCommand());
        }
        if (other.hasRobotControl()) {
          mergeRobotControl(other.getRobotControl());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        if (hasSimulatorCommand()) {
          if (!getSimulatorCommand().isInitialized()) {
            return false;
          }
        }
        if (hasRobotControl()) {
          if (!getRobotControl().isInitialized()) {
            return false;
          }
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        proto.simulation.SslSimulationSynchronous.SimulationSyncRequest parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (proto.simulation.SslSimulationSynchronous.SimulationSyncRequest) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private float simStep_ ;
      /**
       * <pre>
       * The simulation step [s] to perform
       * </pre>
       *
       * <code>optional float sim_step = 1;</code>
       */
      public boolean hasSimStep() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <pre>
       * The simulation step [s] to perform
       * </pre>
       *
       * <code>optional float sim_step = 1;</code>
       */
      public float getSimStep() {
        return simStep_;
      }
      /**
       * <pre>
       * The simulation step [s] to perform
       * </pre>
       *
       * <code>optional float sim_step = 1;</code>
       */
      public Builder setSimStep(float value) {
        bitField0_ |= 0x00000001;
        simStep_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The simulation step [s] to perform
       * </pre>
       *
       * <code>optional float sim_step = 1;</code>
       */
      public Builder clearSimStep() {
        bitField0_ = (bitField0_ & ~0x00000001);
        simStep_ = 0F;
        onChanged();
        return this;
      }

      private proto.simulation.SslSimulationControl.SimulatorCommand simulatorCommand_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          proto.simulation.SslSimulationControl.SimulatorCommand, proto.simulation.SslSimulationControl.SimulatorCommand.Builder, proto.simulation.SslSimulationControl.SimulatorCommandOrBuilder> simulatorCommandBuilder_;
      /**
       * <pre>
       * An optional simulator command
       * </pre>
       *
       * <code>optional .proto.simulation.SimulatorCommand simulator_command = 2;</code>
       */
      public boolean hasSimulatorCommand() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <pre>
       * An optional simulator command
       * </pre>
       *
       * <code>optional .proto.simulation.SimulatorCommand simulator_command = 2;</code>
       */
      public proto.simulation.SslSimulationControl.SimulatorCommand getSimulatorCommand() {
        if (simulatorCommandBuilder_ == null) {
          return simulatorCommand_ == null ? proto.simulation.SslSimulationControl.SimulatorCommand.getDefaultInstance() : simulatorCommand_;
        } else {
          return simulatorCommandBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       * An optional simulator command
       * </pre>
       *
       * <code>optional .proto.simulation.SimulatorCommand simulator_command = 2;</code>
       */
      public Builder setSimulatorCommand(proto.simulation.SslSimulationControl.SimulatorCommand value) {
        if (simulatorCommandBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          simulatorCommand_ = value;
          onChanged();
        } else {
          simulatorCommandBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <pre>
       * An optional simulator command
       * </pre>
       *
       * <code>optional .proto.simulation.SimulatorCommand simulator_command = 2;</code>
       */
      public Builder setSimulatorCommand(
          proto.simulation.SslSimulationControl.SimulatorCommand.Builder builderForValue) {
        if (simulatorCommandBuilder_ == null) {
          simulatorCommand_ = builderForValue.build();
          onChanged();
        } else {
          simulatorCommandBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <pre>
       * An optional simulator command
       * </pre>
       *
       * <code>optional .proto.simulation.SimulatorCommand simulator_command = 2;</code>
       */
      public Builder mergeSimulatorCommand(proto.simulation.SslSimulationControl.SimulatorCommand value) {
        if (simulatorCommandBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              simulatorCommand_ != null &&
              simulatorCommand_ != proto.simulation.SslSimulationControl.SimulatorCommand.getDefaultInstance()) {
            simulatorCommand_ =
              proto.simulation.SslSimulationControl.SimulatorCommand.newBuilder(simulatorCommand_).mergeFrom(value).buildPartial();
          } else {
            simulatorCommand_ = value;
          }
          onChanged();
        } else {
          simulatorCommandBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <pre>
       * An optional simulator command
       * </pre>
       *
       * <code>optional .proto.simulation.SimulatorCommand simulator_command = 2;</code>
       */
      public Builder clearSimulatorCommand() {
        if (simulatorCommandBuilder_ == null) {
          simulatorCommand_ = null;
          onChanged();
        } else {
          simulatorCommandBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      /**
       * <pre>
       * An optional simulator command
       * </pre>
       *
       * <code>optional .proto.simulation.SimulatorCommand simulator_command = 2;</code>
       */
      public proto.simulation.SslSimulationControl.SimulatorCommand.Builder getSimulatorCommandBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getSimulatorCommandFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       * An optional simulator command
       * </pre>
       *
       * <code>optional .proto.simulation.SimulatorCommand simulator_command = 2;</code>
       */
      public proto.simulation.SslSimulationControl.SimulatorCommandOrBuilder getSimulatorCommandOrBuilder() {
        if (simulatorCommandBuilder_ != null) {
          return simulatorCommandBuilder_.getMessageOrBuilder();
        } else {
          return simulatorCommand_ == null ?
              proto.simulation.SslSimulationControl.SimulatorCommand.getDefaultInstance() : simulatorCommand_;
        }
      }
      /**
       * <pre>
       * An optional simulator command
       * </pre>
       *
       * <code>optional .proto.simulation.SimulatorCommand simulator_command = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          proto.simulation.SslSimulationControl.SimulatorCommand, proto.simulation.SslSimulationControl.SimulatorCommand.Builder, proto.simulation.SslSimulationControl.SimulatorCommandOrBuilder> 
          getSimulatorCommandFieldBuilder() {
        if (simulatorCommandBuilder_ == null) {
          simulatorCommandBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              proto.simulation.SslSimulationControl.SimulatorCommand, proto.simulation.SslSimulationControl.SimulatorCommand.Builder, proto.simulation.SslSimulationControl.SimulatorCommandOrBuilder>(
                  getSimulatorCommand(),
                  getParentForChildren(),
                  isClean());
          simulatorCommand_ = null;
        }
        return simulatorCommandBuilder_;
      }

      private proto.simulation.SslSimulationRobotControl.RobotControl robotControl_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          proto.simulation.SslSimulationRobotControl.RobotControl, proto.simulation.SslSimulationRobotControl.RobotControl.Builder, proto.simulation.SslSimulationRobotControl.RobotControlOrBuilder> robotControlBuilder_;
      /**
       * <pre>
       * An optional robot control command
       * </pre>
       *
       * <code>optional .proto.simulation.RobotControl robot_control = 3;</code>
       */
      public boolean hasRobotControl() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <pre>
       * An optional robot control command
       * </pre>
       *
       * <code>optional .proto.simulation.RobotControl robot_control = 3;</code>
       */
      public proto.simulation.SslSimulationRobotControl.RobotControl getRobotControl() {
        if (robotControlBuilder_ == null) {
          return robotControl_ == null ? proto.simulation.SslSimulationRobotControl.RobotControl.getDefaultInstance() : robotControl_;
        } else {
          return robotControlBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       * An optional robot control command
       * </pre>
       *
       * <code>optional .proto.simulation.RobotControl robot_control = 3;</code>
       */
      public Builder setRobotControl(proto.simulation.SslSimulationRobotControl.RobotControl value) {
        if (robotControlBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          robotControl_ = value;
          onChanged();
        } else {
          robotControlBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <pre>
       * An optional robot control command
       * </pre>
       *
       * <code>optional .proto.simulation.RobotControl robot_control = 3;</code>
       */
      public Builder setRobotControl(
          proto.simulation.SslSimulationRobotControl.RobotControl.Builder builderForValue) {
        if (robotControlBuilder_ == null) {
          robotControl_ = builderForValue.build();
          onChanged();
        } else {
          robotControlBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <pre>
       * An optional robot control command
       * </pre>
       *
       * <code>optional .proto.simulation.RobotControl robot_control = 3;</code>
       */
      public Builder mergeRobotControl(proto.simulation.SslSimulationRobotControl.RobotControl value) {
        if (robotControlBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004) &&
              robotControl_ != null &&
              robotControl_ != proto.simulation.SslSimulationRobotControl.RobotControl.getDefaultInstance()) {
            robotControl_ =
              proto.simulation.SslSimulationRobotControl.RobotControl.newBuilder(robotControl_).mergeFrom(value).buildPartial();
          } else {
            robotControl_ = value;
          }
          onChanged();
        } else {
          robotControlBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000004;
        return this;
      }
      /**
       * <pre>
       * An optional robot control command
       * </pre>
       *
       * <code>optional .proto.simulation.RobotControl robot_control = 3;</code>
       */
      public Builder clearRobotControl() {
        if (robotControlBuilder_ == null) {
          robotControl_ = null;
          onChanged();
        } else {
          robotControlBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }
      /**
       * <pre>
       * An optional robot control command
       * </pre>
       *
       * <code>optional .proto.simulation.RobotControl robot_control = 3;</code>
       */
      public proto.simulation.SslSimulationRobotControl.RobotControl.Builder getRobotControlBuilder() {
        bitField0_ |= 0x00000004;
        onChanged();
        return getRobotControlFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       * An optional robot control command
       * </pre>
       *
       * <code>optional .proto.simulation.RobotControl robot_control = 3;</code>
       */
      public proto.simulation.SslSimulationRobotControl.RobotControlOrBuilder getRobotControlOrBuilder() {
        if (robotControlBuilder_ != null) {
          return robotControlBuilder_.getMessageOrBuilder();
        } else {
          return robotControl_ == null ?
              proto.simulation.SslSimulationRobotControl.RobotControl.getDefaultInstance() : robotControl_;
        }
      }
      /**
       * <pre>
       * An optional robot control command
       * </pre>
       *
       * <code>optional .proto.simulation.RobotControl robot_control = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          proto.simulation.SslSimulationRobotControl.RobotControl, proto.simulation.SslSimulationRobotControl.RobotControl.Builder, proto.simulation.SslSimulationRobotControl.RobotControlOrBuilder> 
          getRobotControlFieldBuilder() {
        if (robotControlBuilder_ == null) {
          robotControlBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              proto.simulation.SslSimulationRobotControl.RobotControl, proto.simulation.SslSimulationRobotControl.RobotControl.Builder, proto.simulation.SslSimulationRobotControl.RobotControlOrBuilder>(
                  getRobotControl(),
                  getParentForChildren(),
                  isClean());
          robotControl_ = null;
        }
        return robotControlBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:proto.simulation.SimulationSyncRequest)
    }

    // @@protoc_insertion_point(class_scope:proto.simulation.SimulationSyncRequest)
    private static final proto.simulation.SslSimulationSynchronous.SimulationSyncRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new proto.simulation.SslSimulationSynchronous.SimulationSyncRequest();
    }

    public static proto.simulation.SslSimulationSynchronous.SimulationSyncRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<SimulationSyncRequest>
        PARSER = new com.google.protobuf.AbstractParser<SimulationSyncRequest>() {
      @java.lang.Override
      public SimulationSyncRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SimulationSyncRequest(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SimulationSyncRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SimulationSyncRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public proto.simulation.SslSimulationSynchronous.SimulationSyncRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface SimulationSyncResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proto.simulation.SimulationSyncResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * List of detection frames for all cameras with the state after the simulation step in the request was performed
     * </pre>
     *
     * <code>repeated .proto.simulation.SSL_DetectionFrame detection = 1;</code>
     */
    java.util.List<proto.simulation.SslVisionDetection.SSL_DetectionFrame> 
        getDetectionList();
    /**
     * <pre>
     * List of detection frames for all cameras with the state after the simulation step in the request was performed
     * </pre>
     *
     * <code>repeated .proto.simulation.SSL_DetectionFrame detection = 1;</code>
     */
    proto.simulation.SslVisionDetection.SSL_DetectionFrame getDetection(int index);
    /**
     * <pre>
     * List of detection frames for all cameras with the state after the simulation step in the request was performed
     * </pre>
     *
     * <code>repeated .proto.simulation.SSL_DetectionFrame detection = 1;</code>
     */
    int getDetectionCount();
    /**
     * <pre>
     * List of detection frames for all cameras with the state after the simulation step in the request was performed
     * </pre>
     *
     * <code>repeated .proto.simulation.SSL_DetectionFrame detection = 1;</code>
     */
    java.util.List<? extends proto.simulation.SslVisionDetection.SSL_DetectionFrameOrBuilder> 
        getDetectionOrBuilderList();
    /**
     * <pre>
     * List of detection frames for all cameras with the state after the simulation step in the request was performed
     * </pre>
     *
     * <code>repeated .proto.simulation.SSL_DetectionFrame detection = 1;</code>
     */
    proto.simulation.SslVisionDetection.SSL_DetectionFrameOrBuilder getDetectionOrBuilder(
        int index);

    /**
     * <pre>
     * An optional robot control response
     * </pre>
     *
     * <code>optional .proto.simulation.RobotControlResponse robot_control_response = 2;</code>
     */
    boolean hasRobotControlResponse();
    /**
     * <pre>
     * An optional robot control response
     * </pre>
     *
     * <code>optional .proto.simulation.RobotControlResponse robot_control_response = 2;</code>
     */
    proto.simulation.SslSimulationRobotFeedback.RobotControlResponse getRobotControlResponse();
    /**
     * <pre>
     * An optional robot control response
     * </pre>
     *
     * <code>optional .proto.simulation.RobotControlResponse robot_control_response = 2;</code>
     */
    proto.simulation.SslSimulationRobotFeedback.RobotControlResponseOrBuilder getRobotControlResponseOrBuilder();
  }
  /**
   * <pre>
   * Response to last SimulationSyncRequest
   * </pre>
   *
   * Protobuf type {@code proto.simulation.SimulationSyncResponse}
   */
  public  static final class SimulationSyncResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:proto.simulation.SimulationSyncResponse)
      SimulationSyncResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use SimulationSyncResponse.newBuilder() to construct.
    private SimulationSyncResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private SimulationSyncResponse() {
      detection_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SimulationSyncResponse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                detection_ = new java.util.ArrayList<proto.simulation.SslVisionDetection.SSL_DetectionFrame>();
                mutable_bitField0_ |= 0x00000001;
              }
              detection_.add(
                  input.readMessage(proto.simulation.SslVisionDetection.SSL_DetectionFrame.PARSER, extensionRegistry));
              break;
            }
            case 18: {
              proto.simulation.SslSimulationRobotFeedback.RobotControlResponse.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) == 0x00000001)) {
                subBuilder = robotControlResponse_.toBuilder();
              }
              robotControlResponse_ = input.readMessage(proto.simulation.SslSimulationRobotFeedback.RobotControlResponse.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(robotControlResponse_);
                robotControlResponse_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          detection_ = java.util.Collections.unmodifiableList(detection_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return proto.simulation.SslSimulationSynchronous.internal_static_proto_simulation_SimulationSyncResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return proto.simulation.SslSimulationSynchronous.internal_static_proto_simulation_SimulationSyncResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              proto.simulation.SslSimulationSynchronous.SimulationSyncResponse.class, proto.simulation.SslSimulationSynchronous.SimulationSyncResponse.Builder.class);
    }

    private int bitField0_;
    public static final int DETECTION_FIELD_NUMBER = 1;
    private java.util.List<proto.simulation.SslVisionDetection.SSL_DetectionFrame> detection_;
    /**
     * <pre>
     * List of detection frames for all cameras with the state after the simulation step in the request was performed
     * </pre>
     *
     * <code>repeated .proto.simulation.SSL_DetectionFrame detection = 1;</code>
     */
    public java.util.List<proto.simulation.SslVisionDetection.SSL_DetectionFrame> getDetectionList() {
      return detection_;
    }
    /**
     * <pre>
     * List of detection frames for all cameras with the state after the simulation step in the request was performed
     * </pre>
     *
     * <code>repeated .proto.simulation.SSL_DetectionFrame detection = 1;</code>
     */
    public java.util.List<? extends proto.simulation.SslVisionDetection.SSL_DetectionFrameOrBuilder> 
        getDetectionOrBuilderList() {
      return detection_;
    }
    /**
     * <pre>
     * List of detection frames for all cameras with the state after the simulation step in the request was performed
     * </pre>
     *
     * <code>repeated .proto.simulation.SSL_DetectionFrame detection = 1;</code>
     */
    public int getDetectionCount() {
      return detection_.size();
    }
    /**
     * <pre>
     * List of detection frames for all cameras with the state after the simulation step in the request was performed
     * </pre>
     *
     * <code>repeated .proto.simulation.SSL_DetectionFrame detection = 1;</code>
     */
    public proto.simulation.SslVisionDetection.SSL_DetectionFrame getDetection(int index) {
      return detection_.get(index);
    }
    /**
     * <pre>
     * List of detection frames for all cameras with the state after the simulation step in the request was performed
     * </pre>
     *
     * <code>repeated .proto.simulation.SSL_DetectionFrame detection = 1;</code>
     */
    public proto.simulation.SslVisionDetection.SSL_DetectionFrameOrBuilder getDetectionOrBuilder(
        int index) {
      return detection_.get(index);
    }

    public static final int ROBOT_CONTROL_RESPONSE_FIELD_NUMBER = 2;
    private proto.simulation.SslSimulationRobotFeedback.RobotControlResponse robotControlResponse_;
    /**
     * <pre>
     * An optional robot control response
     * </pre>
     *
     * <code>optional .proto.simulation.RobotControlResponse robot_control_response = 2;</code>
     */
    public boolean hasRobotControlResponse() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <pre>
     * An optional robot control response
     * </pre>
     *
     * <code>optional .proto.simulation.RobotControlResponse robot_control_response = 2;</code>
     */
    public proto.simulation.SslSimulationRobotFeedback.RobotControlResponse getRobotControlResponse() {
      return robotControlResponse_ == null ? proto.simulation.SslSimulationRobotFeedback.RobotControlResponse.getDefaultInstance() : robotControlResponse_;
    }
    /**
     * <pre>
     * An optional robot control response
     * </pre>
     *
     * <code>optional .proto.simulation.RobotControlResponse robot_control_response = 2;</code>
     */
    public proto.simulation.SslSimulationRobotFeedback.RobotControlResponseOrBuilder getRobotControlResponseOrBuilder() {
      return robotControlResponse_ == null ? proto.simulation.SslSimulationRobotFeedback.RobotControlResponse.getDefaultInstance() : robotControlResponse_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      for (int i = 0; i < getDetectionCount(); i++) {
        if (!getDetection(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      if (hasRobotControlResponse()) {
        if (!getRobotControlResponse().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      for (int i = 0; i < detection_.size(); i++) {
        output.writeMessage(1, detection_.get(i));
      }
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(2, getRobotControlResponse());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      for (int i = 0; i < detection_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, detection_.get(i));
      }
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getRobotControlResponse());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof proto.simulation.SslSimulationSynchronous.SimulationSyncResponse)) {
        return super.equals(obj);
      }
      proto.simulation.SslSimulationSynchronous.SimulationSyncResponse other = (proto.simulation.SslSimulationSynchronous.SimulationSyncResponse) obj;

      boolean result = true;
      result = result && getDetectionList()
          .equals(other.getDetectionList());
      result = result && (hasRobotControlResponse() == other.hasRobotControlResponse());
      if (hasRobotControlResponse()) {
        result = result && getRobotControlResponse()
            .equals(other.getRobotControlResponse());
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (getDetectionCount() > 0) {
        hash = (37 * hash) + DETECTION_FIELD_NUMBER;
        hash = (53 * hash) + getDetectionList().hashCode();
      }
      if (hasRobotControlResponse()) {
        hash = (37 * hash) + ROBOT_CONTROL_RESPONSE_FIELD_NUMBER;
        hash = (53 * hash) + getRobotControlResponse().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static proto.simulation.SslSimulationSynchronous.SimulationSyncResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.simulation.SslSimulationSynchronous.SimulationSyncResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.simulation.SslSimulationSynchronous.SimulationSyncResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.simulation.SslSimulationSynchronous.SimulationSyncResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.simulation.SslSimulationSynchronous.SimulationSyncResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static proto.simulation.SslSimulationSynchronous.SimulationSyncResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static proto.simulation.SslSimulationSynchronous.SimulationSyncResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto.simulation.SslSimulationSynchronous.SimulationSyncResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto.simulation.SslSimulationSynchronous.SimulationSyncResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static proto.simulation.SslSimulationSynchronous.SimulationSyncResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static proto.simulation.SslSimulationSynchronous.SimulationSyncResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static proto.simulation.SslSimulationSynchronous.SimulationSyncResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(proto.simulation.SslSimulationSynchronous.SimulationSyncResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Response to last SimulationSyncRequest
     * </pre>
     *
     * Protobuf type {@code proto.simulation.SimulationSyncResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proto.simulation.SimulationSyncResponse)
        proto.simulation.SslSimulationSynchronous.SimulationSyncResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return proto.simulation.SslSimulationSynchronous.internal_static_proto_simulation_SimulationSyncResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return proto.simulation.SslSimulationSynchronous.internal_static_proto_simulation_SimulationSyncResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                proto.simulation.SslSimulationSynchronous.SimulationSyncResponse.class, proto.simulation.SslSimulationSynchronous.SimulationSyncResponse.Builder.class);
      }

      // Construct using proto.simulation.SslSimulationSynchronous.SimulationSyncResponse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getDetectionFieldBuilder();
          getRobotControlResponseFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        if (detectionBuilder_ == null) {
          detection_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          detectionBuilder_.clear();
        }
        if (robotControlResponseBuilder_ == null) {
          robotControlResponse_ = null;
        } else {
          robotControlResponseBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return proto.simulation.SslSimulationSynchronous.internal_static_proto_simulation_SimulationSyncResponse_descriptor;
      }

      @java.lang.Override
      public proto.simulation.SslSimulationSynchronous.SimulationSyncResponse getDefaultInstanceForType() {
        return proto.simulation.SslSimulationSynchronous.SimulationSyncResponse.getDefaultInstance();
      }

      @java.lang.Override
      public proto.simulation.SslSimulationSynchronous.SimulationSyncResponse build() {
        proto.simulation.SslSimulationSynchronous.SimulationSyncResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public proto.simulation.SslSimulationSynchronous.SimulationSyncResponse buildPartial() {
        proto.simulation.SslSimulationSynchronous.SimulationSyncResponse result = new proto.simulation.SslSimulationSynchronous.SimulationSyncResponse(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (detectionBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001)) {
            detection_ = java.util.Collections.unmodifiableList(detection_);
            bitField0_ = (bitField0_ & ~0x00000001);
          }
          result.detection_ = detection_;
        } else {
          result.detection_ = detectionBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000001;
        }
        if (robotControlResponseBuilder_ == null) {
          result.robotControlResponse_ = robotControlResponse_;
        } else {
          result.robotControlResponse_ = robotControlResponseBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof proto.simulation.SslSimulationSynchronous.SimulationSyncResponse) {
          return mergeFrom((proto.simulation.SslSimulationSynchronous.SimulationSyncResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(proto.simulation.SslSimulationSynchronous.SimulationSyncResponse other) {
        if (other == proto.simulation.SslSimulationSynchronous.SimulationSyncResponse.getDefaultInstance()) return this;
        if (detectionBuilder_ == null) {
          if (!other.detection_.isEmpty()) {
            if (detection_.isEmpty()) {
              detection_ = other.detection_;
              bitField0_ = (bitField0_ & ~0x00000001);
            } else {
              ensureDetectionIsMutable();
              detection_.addAll(other.detection_);
            }
            onChanged();
          }
        } else {
          if (!other.detection_.isEmpty()) {
            if (detectionBuilder_.isEmpty()) {
              detectionBuilder_.dispose();
              detectionBuilder_ = null;
              detection_ = other.detection_;
              bitField0_ = (bitField0_ & ~0x00000001);
              detectionBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getDetectionFieldBuilder() : null;
            } else {
              detectionBuilder_.addAllMessages(other.detection_);
            }
          }
        }
        if (other.hasRobotControlResponse()) {
          mergeRobotControlResponse(other.getRobotControlResponse());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        for (int i = 0; i < getDetectionCount(); i++) {
          if (!getDetection(i).isInitialized()) {
            return false;
          }
        }
        if (hasRobotControlResponse()) {
          if (!getRobotControlResponse().isInitialized()) {
            return false;
          }
        }
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        proto.simulation.SslSimulationSynchronous.SimulationSyncResponse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (proto.simulation.SslSimulationSynchronous.SimulationSyncResponse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.util.List<proto.simulation.SslVisionDetection.SSL_DetectionFrame> detection_ =
        java.util.Collections.emptyList();
      private void ensureDetectionIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          detection_ = new java.util.ArrayList<proto.simulation.SslVisionDetection.SSL_DetectionFrame>(detection_);
          bitField0_ |= 0x00000001;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          proto.simulation.SslVisionDetection.SSL_DetectionFrame, proto.simulation.SslVisionDetection.SSL_DetectionFrame.Builder, proto.simulation.SslVisionDetection.SSL_DetectionFrameOrBuilder> detectionBuilder_;

      /**
       * <pre>
       * List of detection frames for all cameras with the state after the simulation step in the request was performed
       * </pre>
       *
       * <code>repeated .proto.simulation.SSL_DetectionFrame detection = 1;</code>
       */
      public java.util.List<proto.simulation.SslVisionDetection.SSL_DetectionFrame> getDetectionList() {
        if (detectionBuilder_ == null) {
          return java.util.Collections.unmodifiableList(detection_);
        } else {
          return detectionBuilder_.getMessageList();
        }
      }
      /**
       * <pre>
       * List of detection frames for all cameras with the state after the simulation step in the request was performed
       * </pre>
       *
       * <code>repeated .proto.simulation.SSL_DetectionFrame detection = 1;</code>
       */
      public int getDetectionCount() {
        if (detectionBuilder_ == null) {
          return detection_.size();
        } else {
          return detectionBuilder_.getCount();
        }
      }
      /**
       * <pre>
       * List of detection frames for all cameras with the state after the simulation step in the request was performed
       * </pre>
       *
       * <code>repeated .proto.simulation.SSL_DetectionFrame detection = 1;</code>
       */
      public proto.simulation.SslVisionDetection.SSL_DetectionFrame getDetection(int index) {
        if (detectionBuilder_ == null) {
          return detection_.get(index);
        } else {
          return detectionBuilder_.getMessage(index);
        }
      }
      /**
       * <pre>
       * List of detection frames for all cameras with the state after the simulation step in the request was performed
       * </pre>
       *
       * <code>repeated .proto.simulation.SSL_DetectionFrame detection = 1;</code>
       */
      public Builder setDetection(
          int index, proto.simulation.SslVisionDetection.SSL_DetectionFrame value) {
        if (detectionBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDetectionIsMutable();
          detection_.set(index, value);
          onChanged();
        } else {
          detectionBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       * List of detection frames for all cameras with the state after the simulation step in the request was performed
       * </pre>
       *
       * <code>repeated .proto.simulation.SSL_DetectionFrame detection = 1;</code>
       */
      public Builder setDetection(
          int index, proto.simulation.SslVisionDetection.SSL_DetectionFrame.Builder builderForValue) {
        if (detectionBuilder_ == null) {
          ensureDetectionIsMutable();
          detection_.set(index, builderForValue.build());
          onChanged();
        } else {
          detectionBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * List of detection frames for all cameras with the state after the simulation step in the request was performed
       * </pre>
       *
       * <code>repeated .proto.simulation.SSL_DetectionFrame detection = 1;</code>
       */
      public Builder addDetection(proto.simulation.SslVisionDetection.SSL_DetectionFrame value) {
        if (detectionBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDetectionIsMutable();
          detection_.add(value);
          onChanged();
        } else {
          detectionBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <pre>
       * List of detection frames for all cameras with the state after the simulation step in the request was performed
       * </pre>
       *
       * <code>repeated .proto.simulation.SSL_DetectionFrame detection = 1;</code>
       */
      public Builder addDetection(
          int index, proto.simulation.SslVisionDetection.SSL_DetectionFrame value) {
        if (detectionBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureDetectionIsMutable();
          detection_.add(index, value);
          onChanged();
        } else {
          detectionBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <pre>
       * List of detection frames for all cameras with the state after the simulation step in the request was performed
       * </pre>
       *
       * <code>repeated .proto.simulation.SSL_DetectionFrame detection = 1;</code>
       */
      public Builder addDetection(
          proto.simulation.SslVisionDetection.SSL_DetectionFrame.Builder builderForValue) {
        if (detectionBuilder_ == null) {
          ensureDetectionIsMutable();
          detection_.add(builderForValue.build());
          onChanged();
        } else {
          detectionBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * List of detection frames for all cameras with the state after the simulation step in the request was performed
       * </pre>
       *
       * <code>repeated .proto.simulation.SSL_DetectionFrame detection = 1;</code>
       */
      public Builder addDetection(
          int index, proto.simulation.SslVisionDetection.SSL_DetectionFrame.Builder builderForValue) {
        if (detectionBuilder_ == null) {
          ensureDetectionIsMutable();
          detection_.add(index, builderForValue.build());
          onChanged();
        } else {
          detectionBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <pre>
       * List of detection frames for all cameras with the state after the simulation step in the request was performed
       * </pre>
       *
       * <code>repeated .proto.simulation.SSL_DetectionFrame detection = 1;</code>
       */
      public Builder addAllDetection(
          java.lang.Iterable<? extends proto.simulation.SslVisionDetection.SSL_DetectionFrame> values) {
        if (detectionBuilder_ == null) {
          ensureDetectionIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, detection_);
          onChanged();
        } else {
          detectionBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <pre>
       * List of detection frames for all cameras with the state after the simulation step in the request was performed
       * </pre>
       *
       * <code>repeated .proto.simulation.SSL_DetectionFrame detection = 1;</code>
       */
      public Builder clearDetection() {
        if (detectionBuilder_ == null) {
          detection_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000001);
          onChanged();
        } else {
          detectionBuilder_.clear();
        }
        return this;
      }
      /**
       * <pre>
       * List of detection frames for all cameras with the state after the simulation step in the request was performed
       * </pre>
       *
       * <code>repeated .proto.simulation.SSL_DetectionFrame detection = 1;</code>
       */
      public Builder removeDetection(int index) {
        if (detectionBuilder_ == null) {
          ensureDetectionIsMutable();
          detection_.remove(index);
          onChanged();
        } else {
          detectionBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <pre>
       * List of detection frames for all cameras with the state after the simulation step in the request was performed
       * </pre>
       *
       * <code>repeated .proto.simulation.SSL_DetectionFrame detection = 1;</code>
       */
      public proto.simulation.SslVisionDetection.SSL_DetectionFrame.Builder getDetectionBuilder(
          int index) {
        return getDetectionFieldBuilder().getBuilder(index);
      }
      /**
       * <pre>
       * List of detection frames for all cameras with the state after the simulation step in the request was performed
       * </pre>
       *
       * <code>repeated .proto.simulation.SSL_DetectionFrame detection = 1;</code>
       */
      public proto.simulation.SslVisionDetection.SSL_DetectionFrameOrBuilder getDetectionOrBuilder(
          int index) {
        if (detectionBuilder_ == null) {
          return detection_.get(index);  } else {
          return detectionBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <pre>
       * List of detection frames for all cameras with the state after the simulation step in the request was performed
       * </pre>
       *
       * <code>repeated .proto.simulation.SSL_DetectionFrame detection = 1;</code>
       */
      public java.util.List<? extends proto.simulation.SslVisionDetection.SSL_DetectionFrameOrBuilder> 
           getDetectionOrBuilderList() {
        if (detectionBuilder_ != null) {
          return detectionBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(detection_);
        }
      }
      /**
       * <pre>
       * List of detection frames for all cameras with the state after the simulation step in the request was performed
       * </pre>
       *
       * <code>repeated .proto.simulation.SSL_DetectionFrame detection = 1;</code>
       */
      public proto.simulation.SslVisionDetection.SSL_DetectionFrame.Builder addDetectionBuilder() {
        return getDetectionFieldBuilder().addBuilder(
            proto.simulation.SslVisionDetection.SSL_DetectionFrame.getDefaultInstance());
      }
      /**
       * <pre>
       * List of detection frames for all cameras with the state after the simulation step in the request was performed
       * </pre>
       *
       * <code>repeated .proto.simulation.SSL_DetectionFrame detection = 1;</code>
       */
      public proto.simulation.SslVisionDetection.SSL_DetectionFrame.Builder addDetectionBuilder(
          int index) {
        return getDetectionFieldBuilder().addBuilder(
            index, proto.simulation.SslVisionDetection.SSL_DetectionFrame.getDefaultInstance());
      }
      /**
       * <pre>
       * List of detection frames for all cameras with the state after the simulation step in the request was performed
       * </pre>
       *
       * <code>repeated .proto.simulation.SSL_DetectionFrame detection = 1;</code>
       */
      public java.util.List<proto.simulation.SslVisionDetection.SSL_DetectionFrame.Builder> 
           getDetectionBuilderList() {
        return getDetectionFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          proto.simulation.SslVisionDetection.SSL_DetectionFrame, proto.simulation.SslVisionDetection.SSL_DetectionFrame.Builder, proto.simulation.SslVisionDetection.SSL_DetectionFrameOrBuilder> 
          getDetectionFieldBuilder() {
        if (detectionBuilder_ == null) {
          detectionBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              proto.simulation.SslVisionDetection.SSL_DetectionFrame, proto.simulation.SslVisionDetection.SSL_DetectionFrame.Builder, proto.simulation.SslVisionDetection.SSL_DetectionFrameOrBuilder>(
                  detection_,
                  ((bitField0_ & 0x00000001) == 0x00000001),
                  getParentForChildren(),
                  isClean());
          detection_ = null;
        }
        return detectionBuilder_;
      }

      private proto.simulation.SslSimulationRobotFeedback.RobotControlResponse robotControlResponse_ = null;
      private com.google.protobuf.SingleFieldBuilderV3<
          proto.simulation.SslSimulationRobotFeedback.RobotControlResponse, proto.simulation.SslSimulationRobotFeedback.RobotControlResponse.Builder, proto.simulation.SslSimulationRobotFeedback.RobotControlResponseOrBuilder> robotControlResponseBuilder_;
      /**
       * <pre>
       * An optional robot control response
       * </pre>
       *
       * <code>optional .proto.simulation.RobotControlResponse robot_control_response = 2;</code>
       */
      public boolean hasRobotControlResponse() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <pre>
       * An optional robot control response
       * </pre>
       *
       * <code>optional .proto.simulation.RobotControlResponse robot_control_response = 2;</code>
       */
      public proto.simulation.SslSimulationRobotFeedback.RobotControlResponse getRobotControlResponse() {
        if (robotControlResponseBuilder_ == null) {
          return robotControlResponse_ == null ? proto.simulation.SslSimulationRobotFeedback.RobotControlResponse.getDefaultInstance() : robotControlResponse_;
        } else {
          return robotControlResponseBuilder_.getMessage();
        }
      }
      /**
       * <pre>
       * An optional robot control response
       * </pre>
       *
       * <code>optional .proto.simulation.RobotControlResponse robot_control_response = 2;</code>
       */
      public Builder setRobotControlResponse(proto.simulation.SslSimulationRobotFeedback.RobotControlResponse value) {
        if (robotControlResponseBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          robotControlResponse_ = value;
          onChanged();
        } else {
          robotControlResponseBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <pre>
       * An optional robot control response
       * </pre>
       *
       * <code>optional .proto.simulation.RobotControlResponse robot_control_response = 2;</code>
       */
      public Builder setRobotControlResponse(
          proto.simulation.SslSimulationRobotFeedback.RobotControlResponse.Builder builderForValue) {
        if (robotControlResponseBuilder_ == null) {
          robotControlResponse_ = builderForValue.build();
          onChanged();
        } else {
          robotControlResponseBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <pre>
       * An optional robot control response
       * </pre>
       *
       * <code>optional .proto.simulation.RobotControlResponse robot_control_response = 2;</code>
       */
      public Builder mergeRobotControlResponse(proto.simulation.SslSimulationRobotFeedback.RobotControlResponse value) {
        if (robotControlResponseBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              robotControlResponse_ != null &&
              robotControlResponse_ != proto.simulation.SslSimulationRobotFeedback.RobotControlResponse.getDefaultInstance()) {
            robotControlResponse_ =
              proto.simulation.SslSimulationRobotFeedback.RobotControlResponse.newBuilder(robotControlResponse_).mergeFrom(value).buildPartial();
          } else {
            robotControlResponse_ = value;
          }
          onChanged();
        } else {
          robotControlResponseBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <pre>
       * An optional robot control response
       * </pre>
       *
       * <code>optional .proto.simulation.RobotControlResponse robot_control_response = 2;</code>
       */
      public Builder clearRobotControlResponse() {
        if (robotControlResponseBuilder_ == null) {
          robotControlResponse_ = null;
          onChanged();
        } else {
          robotControlResponseBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      /**
       * <pre>
       * An optional robot control response
       * </pre>
       *
       * <code>optional .proto.simulation.RobotControlResponse robot_control_response = 2;</code>
       */
      public proto.simulation.SslSimulationRobotFeedback.RobotControlResponse.Builder getRobotControlResponseBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getRobotControlResponseFieldBuilder().getBuilder();
      }
      /**
       * <pre>
       * An optional robot control response
       * </pre>
       *
       * <code>optional .proto.simulation.RobotControlResponse robot_control_response = 2;</code>
       */
      public proto.simulation.SslSimulationRobotFeedback.RobotControlResponseOrBuilder getRobotControlResponseOrBuilder() {
        if (robotControlResponseBuilder_ != null) {
          return robotControlResponseBuilder_.getMessageOrBuilder();
        } else {
          return robotControlResponse_ == null ?
              proto.simulation.SslSimulationRobotFeedback.RobotControlResponse.getDefaultInstance() : robotControlResponse_;
        }
      }
      /**
       * <pre>
       * An optional robot control response
       * </pre>
       *
       * <code>optional .proto.simulation.RobotControlResponse robot_control_response = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          proto.simulation.SslSimulationRobotFeedback.RobotControlResponse, proto.simulation.SslSimulationRobotFeedback.RobotControlResponse.Builder, proto.simulation.SslSimulationRobotFeedback.RobotControlResponseOrBuilder> 
          getRobotControlResponseFieldBuilder() {
        if (robotControlResponseBuilder_ == null) {
          robotControlResponseBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              proto.simulation.SslSimulationRobotFeedback.RobotControlResponse, proto.simulation.SslSimulationRobotFeedback.RobotControlResponse.Builder, proto.simulation.SslSimulationRobotFeedback.RobotControlResponseOrBuilder>(
                  getRobotControlResponse(),
                  getParentForChildren(),
                  isClean());
          robotControlResponse_ = null;
        }
        return robotControlResponseBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:proto.simulation.SimulationSyncResponse)
    }

    // @@protoc_insertion_point(class_scope:proto.simulation.SimulationSyncResponse)
    private static final proto.simulation.SslSimulationSynchronous.SimulationSyncResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new proto.simulation.SslSimulationSynchronous.SimulationSyncResponse();
    }

    public static proto.simulation.SslSimulationSynchronous.SimulationSyncResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<SimulationSyncResponse>
        PARSER = new com.google.protobuf.AbstractParser<SimulationSyncResponse>() {
      @java.lang.Override
      public SimulationSyncResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new SimulationSyncResponse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<SimulationSyncResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SimulationSyncResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public proto.simulation.SslSimulationSynchronous.SimulationSyncResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_simulation_SimulationSyncRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_simulation_SimulationSyncRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proto_simulation_SimulationSyncResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proto_simulation_SimulationSyncResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n ssl_simulation_synchronous.proto\022\020prot" +
      "o.simulation\032\032ssl_vision_detection.proto" +
      "\032#ssl_simulation_robot_feedback.proto\032\"s" +
      "sl_simulation_robot_control.proto\032\034ssl_s" +
      "imulation_control.proto\"\237\001\n\025SimulationSy" +
      "ncRequest\022\020\n\010sim_step\030\001 \001(\002\022=\n\021simulator" +
      "_command\030\002 \001(\0132\".proto.simulation.Simula" +
      "torCommand\0225\n\rrobot_control\030\003 \001(\0132\036.prot" +
      "o.simulation.RobotControl\"\231\001\n\026Simulation" +
      "SyncResponse\0227\n\tdetection\030\001 \003(\0132$.proto." +
      "simulation.SSL_DetectionFrame\022F\n\026robot_c" +
      "ontrol_response\030\002 \001(\0132&.proto.simulation" +
      ".RobotControlResponseB8Z6github.com/Robo" +
      "Cup-SSL/ssl-simulation-protocol/pkg/sim"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          proto.simulation.SslVisionDetection.getDescriptor(),
          proto.simulation.SslSimulationRobotFeedback.getDescriptor(),
          proto.simulation.SslSimulationRobotControl.getDescriptor(),
          proto.simulation.SslSimulationControl.getDescriptor(),
        }, assigner);
    internal_static_proto_simulation_SimulationSyncRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_proto_simulation_SimulationSyncRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_simulation_SimulationSyncRequest_descriptor,
        new java.lang.String[] { "SimStep", "SimulatorCommand", "RobotControl", });
    internal_static_proto_simulation_SimulationSyncResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_proto_simulation_SimulationSyncResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proto_simulation_SimulationSyncResponse_descriptor,
        new java.lang.String[] { "Detection", "RobotControlResponse", });
    proto.simulation.SslVisionDetection.getDescriptor();
    proto.simulation.SslSimulationRobotFeedback.getDescriptor();
    proto.simulation.SslSimulationRobotControl.getDescriptor();
    proto.simulation.SslSimulationControl.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
